#!/usr/bin/perl
# Copyright (c) 2025-2026 the PCL authors
# This is free software; you can redistribute it and/or modify it under the
# same terms as the Perl 5 programming language system itself.
# SPDX-License-Identifier: Artistic-1.0-Perl OR GPL-1.0-or-later

# fmtlisp FILE.lisp — reformat a CL file in place using emacs
die "Usage: fmtlisp FILE.lisp\n" unless @ARGV == 1;
exec "emacs", "--batch", $ARGV[0],
     "--eval", "(setq-default indent-tabs-mode nil)",
     "--eval", "(indent-region (point-min) (point-max))",
     "-f", "save-buffer";
