package Pl::Parser2;

# Parser2 (prototype) — the v2 statement-level pipeline: structured emission
# (Pl::CLForm) instead of an interleaved text stream.  SAME external API as
# Pl::Parser (parse_file / parse_code / parse → CL text with the
# "(in-package :pcl)" marker pl2cl rewrites), so the two pipelines are
# switchable: pl2cl picks this class when PCL_V2=1.
#
# Division of labour while v2 is being written:
#   - statement/scope/sub STRUCTURE is lowered natively to forms here —
#     nested `let`s at declaration sites (scoping by construction), real
#     lambda lists for `my (LIST) = @_` subs, no VOID `*wantarray*` wraps,
#     VarAnnotator-gated unboxed scalars;
#   - every EXPRESSION is first offered to Pl::ExprToCL2 (strict native
#     subset), and otherwise generated by the ORIGINAL machinery — a real
#     Pl::Parser instance (`fallback_parser`) whose `_parse_expression`
#     reuses PExpr + ExprToCL unchanged; its output embeds as a CLForm raw.
#
# Prototype boundary: unsupported statement kinds die with "Parser2 TODO:".

use v5.30;
use strict;
use warnings;
use Moo;
use PPI;
use Pl::Parser;
use Pl::Environment;
use Pl::PExpr;
use Pl::ExprToCL2;
use Pl::VarAnnotator;
use Pl::CLForm qw(raw);

has filename => (is => 'ro', predicate => 1);
has code     => (is => 'ro', predicate => 1);

# Pre-pass result: perl sub name → { cl_name, insensitive } (see ExprToCL2).
has sub_info => (is => 'rw', default => sub { {} });

has environment => (is => 'lazy');
sub _build_environment {
  my $self = shift;
  return Pl::Environment->new(
    source_file => $self->has_filename ? $self->filename : '-');
}

# The original parser, used purely as the expression-codegen engine.
has fallback_parser => (is => 'lazy');
sub _build_fallback_parser {
  my $self = shift;
  my $p = Pl::Parser->new(
    ($self->has_filename ? (filename => $self->filename) : ()),
    ($self->has_code     ? (code     => $self->code)     : ()),
    environment => $self->environment,
  );
  # Minimal live state _parse_expression's helpers expect (mirrors parse()).
  $p->_sections([]);
  $p->_cur_bucket('runtime');
  $p->_open_section('pcl');
  $p->{_let_bound_vars} = {};
  return $p;
}

sub parse_file { my ($class, $fn, %opts) = @_; return $class->new(filename => $fn)->parse }
sub parse_code { my ($class, $code, %opts) = @_; return $class->new(code => $code)->parse }

sub _source {
  my $self = shift;
  return $self->code if $self->has_code;
  open my $fh, '<', $self->filename or die "Parser2: cannot read " . $self->filename . ": $!";
  local $/;
  return scalar <$fh>;
}

sub parse {
  my $self = shift;
  my $src = Pl::Parser::_preprocess_source(Pl::Parser::_maybe_decode_utf8($self->_source));
  my $doc = PPI::Document->new(\$src) or die "Parser2: PPI parse failed";
  $self->environment->package_stack(['main']);
  $self->environment->state_var_renames({});

  # Pre-pass: collect per-sub facts BEFORE lowering anything, so call sites
  # that precede (or recurse into) a sub's definition see them.
  for my $child ($doc->schildren) {
    next unless $child->isa('PPI::Statement::Sub') && $child->name && $child->block;
    $self->sub_info->{ $child->name } = {
      cl_name     => $self->fallback_parser->_qualified_sub_to_cl($child->name),
      insensitive => $self->_sub_ctx_insensitive($child),
    };
  }

  my (@decls, @defs, @top);
  for my $child ($doc->schildren) {
    if ($child->isa('PPI::Statement::Sub') && $child->name) {
      push @decls, ['p-declare-sub', $self->fallback_parser->_qualified_sub_to_cl($child->name)];
      push @defs, $self->_lower_sub($child);
      next;
    }
    next if $child->isa('PPI::Statement::Include');   # use strict/warnings/... (TODO: modules)
    next if $child->isa('PPI::Statement::Null');
    push @top, $child;
  }
  my @runtime = $self->_lower_block(\@top, Pl::VarAnnotator->analyze(\@top));

  my @out = ('(in-package :pcl)', '');
  push @out, map { Pl::CLForm::to_string($_, 0) } @decls;
  push @out, '(defvar $a (make-p-box nil))', '(defvar $b (make-p-box nil))', '';
  push @out, map { (Pl::CLForm::to_string($_, 0), '') } @defs;
  push @out, map { (Pl::CLForm::to_string($_, 0), '') } @runtime;
  return join("\n", @out);
}

# ---------------------------------------------------------------- subs

sub _lower_sub {
  my ($self, $sub) = @_;
  my $clname = $self->fallback_parser->_qualified_sub_to_cl($sub->name);
  my @stmts = $sub->block->schildren;

  my $params = $self->_extract_params($stmts[0]);
  my @body_stmts = @stmts;
  shift @body_stmts if $params;
  $self->fallback_parser->{_let_bound_vars}{$_} = 1 for @{ $params // [] };

  if ($params) {
    my $rest_txt = join("\n", map { $_->content } @body_stmts);
    my $body_uses_args = $rest_txt =~ /\@_|\$_\[|\bshift\b|\bgoto\b|\bwantarray\b/;
    my $vi = Pl::VarAnnotator->analyze(\@body_stmts, $params);
    if (!$body_uses_args && !grep { !$vi->{$_}{unboxable} } @$params) {
      # Real lambda list (#3): my ($a,$b) = @_ untouched afterwards, params
      # never written un-arithmetically / ref-taken → bind raw, no p-list-=.
      my $ll = ['list', '&optional',
                (map { ['list', $_, '(p-undef)'] } @$params),
                '&rest', '%_args'];
      return ['p-sub', $clname, $ll,
              ['p-args-body', ['block', 'nil', $self->_lower_block(\@body_stmts, $vi)]]];
    }
    # Old convention with boxed params + synthesized list-assign binding.
    $vi->{$_} = { unboxable => 0 } for @$params;
    return ['p-sub', $clname, ['list', '&rest', '%_args'],
            ['p-args-body', ['block', 'nil',
              ['let', ['list', map { ['list', $_, '(make-p-box nil)'] } @$params],
                raw('(let ((*wantarray* nil)) (p-list-= (vector ' . join(' ', @$params) . ') @_))'),
                $self->_lower_block(\@body_stmts, $vi)]]]];
  }

  my $vi = Pl::VarAnnotator->analyze(\@stmts);
  return ['p-sub', $clname, ['list', '&rest', '%_args'],
          ['p-args-body', ['block', 'nil', $self->_lower_block(\@stmts, $vi)]]];
}

# `my ($a, $b) = @_;` → ['$a','$b'] | undef
sub _extract_params {
  my ($self, $stmt) = @_;
  return undef unless $stmt && $stmt->isa('PPI::Statement::Variable');
  my @k = $stmt->schildren;
  return undef unless @k >= 4
    && $k[0]->content eq 'my'
    && $k[1]->isa('PPI::Structure::List')
    && $k[2]->isa('PPI::Token::Operator') && $k[2]->content eq '='
    && $k[3]->isa('PPI::Token::Magic') && $k[3]->content eq '@_';
  my @params = map { $_->content }
               grep { $_->isa('PPI::Token::Symbol') }
               map { $_->tokens } $k[1];
  return undef unless @params && !grep { !/^\$\w+$/ } @params;
  return \@params;
}

# ---------------------------------------------------------------- blocks

# Lower a statement list to forms.  A `my` declaration NESTS the remainder of
# the block inside its `let` — scoping is a property of the tree, never of
# emitted text (the R3 fix).
sub _lower_block {
  my ($self, $stmts, $vi) = @_;
  my @s = grep { ref $_ && !$_->isa('PPI::Statement::Null') } @$stmts;
  return () unless @s;
  my ($first, @rest) = @s;

  # -- my $x [= INIT];  → (let (($x …)) rest...)
  if ($first->isa('PPI::Statement::Variable')) {
    my ($name, $init) = $self->_single_scalar_decl($first);
    die "Parser2 TODO: unsupported declaration: " . $first->content unless $name;
    $self->fallback_parser->{_let_bound_vars}{$name} = 1;
    if ($vi->{$name} && $vi->{$name}{unboxable}) {
      my $initform = defined $init ? $self->_lower_expr($init, $first) : '(p-undef)';
      return (['let', ['list', ['list', $name, $initform]],
               $self->_lower_block(\@rest, $vi)]);
    }
    return (['let', ['list', ['list', $name, '(make-p-box nil)']],
             (defined $init ? (['p-my-=', $name, $self->_lower_expr($init, $first)]) : ()),
             $self->_lower_block(\@rest, $vi)]);
  }

  # -- everything else appends a form and continues at the same depth.
  return ($self->_lower_stmt($first, $vi), $self->_lower_block(\@rest, $vi));
}

sub _lower_stmt {
  my ($self, $stmt, $vi) = @_;

  if ($stmt->isa('PPI::Statement::Compound')) {
    return $self->_lower_compound($stmt, $vi);
  }

  if ($stmt->isa('PPI::Statement::Break')) {
    my @k = _strip_semi($stmt->schildren);
    my $kw = shift(@k)->content;
    die "Parser2 TODO: break statement '$kw'" unless $kw eq 'return';
    my ($expr, $mod, $cond) = _split_modifier(\@k);
    my $form = @$expr
      ? ['p-return', $self->_lower_expr($expr, $stmt)]
      : ['p-return', '(p-undef)'];
    return _apply_modifier($form, $mod, $cond, $self, $stmt);
  }

  if ($stmt->isa('PPI::Statement::Scheduled') || $stmt->isa('PPI::Statement::Package')) {
    die "Parser2 TODO: " . ref($stmt);
  }

  # -- plain expression statement
  my @k = _strip_semi($stmt->schildren);
  my ($expr, $mod, $cond) = _split_modifier(\@k);

  # `$x = RHS;` on a let-bound scalar → native form: `setf` when $x is a raw
  # (unboxed) slot — RHS proven arithmetic by VarAnnotator, so the stored
  # value is a raw number — else `p-my-=` (box-set; never the special-
  # proclaiming p-scalar-=).
  if (!$mod && @$expr >= 3
      && $expr->[0]->isa('PPI::Token::Symbol') && $expr->[0]->content =~ /^\$\w+$/
      && $expr->[1]->isa('PPI::Token::Operator') && $expr->[1]->content eq '=') {
    my $name = $expr->[0]->content;
    my $rhs = [@$expr[2 .. $#$expr]];
    if ($vi->{$name} && $vi->{$name}{unboxable}) {
      return ['setf', $name, $self->_lower_expr($rhs, $stmt)];
    }
    if ($self->fallback_parser->{_let_bound_vars}{$name}) {
      return ['p-my-=', $name, $self->_lower_expr($rhs, $stmt)];
    }
  }

  my $form = $self->_lower_expr($expr, $stmt);
  return _apply_modifier($form, $mod, $cond, $self, $stmt);
}

sub _lower_compound {
  my ($self, $stmt, $vi) = @_;
  my @k = $stmt->schildren;
  my $kw = $k[0]->content;

  if ($kw eq 'if' || $kw eq 'unless') {
    die "Parser2 TODO: elsif" if grep { $_->isa('PPI::Token::Word') && $_->content eq 'elsif' } @k;
    my ($cond_s) = grep { $_->isa('PPI::Structure::Condition') } @k;
    my @blocks   = grep { $_->isa('PPI::Structure::Block') } @k;
    my $cond = $self->_lower_expr([_cond_parts($cond_s)], $stmt);
    $cond = ['p-!', $cond] if $kw eq 'unless';
    return ['p-if', $cond,
            ['progn', $self->_lower_block([$blocks[0]->schildren], $vi)],
            (@blocks > 1 ? (['progn', $self->_lower_block([$blocks[1]->schildren], $vi)]) : ())];
  }

  if ($kw eq 'while' || $kw eq 'until') {
    my ($cond_s) = grep { $_->isa('PPI::Structure::Condition') } @k;
    my ($block)  = grep { $_->isa('PPI::Structure::Block') } @k;
    my $cond = $self->_lower_expr([_cond_parts($cond_s)], $stmt);
    $cond = ['p-!', $cond] if $kw eq 'until';
    return ['p-while', $cond, $self->_lower_block([$block->schildren], $vi)];
  }

  if ($kw eq 'for' || $kw eq 'foreach') {
    my ($list) = grep { $_->isa('PPI::Structure::List') } @k;
    my ($block) = grep { $_->isa('PPI::Structure::Block') } @k;
    my ($var) = grep { $_->isa('PPI::Token::Symbol') } @k;
    die "Parser2 TODO: C-style for / foreach without list" unless $list && $block;
    my $name = $var ? $var->content : '$_';
    $self->fallback_parser->{_let_bound_vars}{$name} = 1;
    my @list_parts = map { $_->schildren } grep { $_->isa('PPI::Statement') } $list->children;
    return ['p-foreach', ['list', $name, $self->_lower_expr(\@list_parts, $stmt, 1)],
            $self->_lower_block([$block->schildren], $vi)];
  }

  die "Parser2 TODO: compound '$kw'";
}

# ---------------------------------------------------------------- expressions

# Native (ExprToCL2 strict subset) or the ORIGINAL expression pipeline.
# $ctx: 0 scalar (default), 1 list — forwarded to the fallback so e.g. a
# foreach list `2..$n` parses as a range, not a scalar flip-flop.
sub _lower_expr {
  my ($self, $parts, $stmt, $ctx) = @_;
  my @parts = _strip_semi(@$parts);
  die "Parser2: empty expression" unless @parts;

  my $native = eval {
    my $expr_o = Pl::PExpr->new(
      e           => \@parts,
      environment => $self->environment,
      parser      => $self->fallback_parser,
    );
    my ($node_id) = $expr_o->parse_expr_to_tree(\@parts);
    Pl::ExprToCL2->new(expr_o => $expr_o, environment => $self->environment,
                       sub_info => $self->sub_info)
                 ->gen_form($node_id);
  };
  return $native if defined $native;

  my $cl = $self->fallback_parser->_parse_expression(\@parts, $stmt, $ctx // 0);
  die "Parser2: expression fallback failed for: " . join(' ', map { $_->content } @parts)
    unless defined $cl;
  # Legacy-boundary parity: the old pipeline rewrites (p-scalar-= $x …) to
  # (p-my-= $x …) for let-bound names inside _emit, which the fallback path
  # bypasses.  Apply the same conversion at the raw boundary (v2-native
  # assignments never need this — they are lowered as p-my-=/setf forms).
  my $lb = $self->fallback_parser->{_let_bound_vars} // {};
  for my $var (keys %$lb) {
    my $pat = quotemeta("(p-scalar-= $var");
    $cl =~ s/$pat(?=[\s)])/(p-my-= $var/g;
  }
  return raw($cl);
}

# ------------------------------------------------------- context sensitivity

# A sub is context-INSENSITIVE when its caller's *wantarray* provably cannot
# be observed: no `wantarray` in the body, and every value it can return —
# each explicit `return EXPR` and the implicit last-statement value — is
# scalar-shaped.  Conservative: any doubt → sensitive (call sites keep the
# dynamic bind, exactly today's behaviour).
sub _sub_ctx_insensitive {
  my ($self, $sub) = @_;
  my $txt = $sub->block->content;
  return 0 if $txt =~ /\bwantarray\b/;

  my $breaks = $sub->block->find('PPI::Statement::Break') || [];
  for my $b (@$breaks) {
    my @k = _strip_semi($b->schildren);
    my $kw = shift @k;
    next unless $kw && $kw->content eq 'return';
    return 0 unless @k;                        # bare `return;` = () vs undef
    my ($expr) = _split_modifier(\@k);
    return 0 unless $self->_expr_scalar_rooted($expr);
  }

  my @stmts = grep { $_->significant && !$_->isa('PPI::Statement::Null') }
              $sub->block->schildren;
  return 0 unless @stmts;
  my $last = $stmts[-1];
  return 1 if $last->isa('PPI::Statement::Break');   # checked above
  if (ref($last) eq 'PPI::Statement' || $last->isa('PPI::Statement::Variable')) {
    my @k = _strip_semi($last->schildren);
    shift @k if @k && $k[0]->isa('PPI::Token::Word') && $k[0]->content eq 'my';
    my ($expr) = _split_modifier(\@k);
    # for `my $x = INIT` the statement value is the assignment value
    return $self->_expr_scalar_rooted($expr) ? 1 : 0;
  }
  return 0;                                   # compound/other tail → sensitive
}

# The expression's ROOT forces scalar shape: an arithmetic/comparison operator
# (coerces its operands, yields one scalar), a scalar variable, a number, or a
# string literal.  A funcall root propagates the caller's context → NOT scalar.
# NOT included: && || // (context-transparent to their right operand) and
# x (repeats lists in list context).
my %SCALAR_ROOT_OP = map { $_ => 1 } qw(+ - * / % ** < > <= >= == != .
                                        eq ne lt gt le ge <=> cmp);
sub _expr_scalar_rooted {
  my ($self, $parts) = @_;
  my @parts = _strip_semi(@{ $parts // [] });
  return 0 unless @parts;
  my $ok = eval {
    my $expr_o = Pl::PExpr->new(
      e           => \@parts,
      environment => $self->environment,
      parser      => $self->fallback_parser,
    );
    my ($id) = $expr_o->parse_expr_to_tree(\@parts);
    while (1) {
      my $node = $expr_o->get_a_node($id);
      my $kids = $expr_o->get_node_children($id);
      if ($expr_o->is_internal_node_type($node)) {
        my $t = $node->{type} // '';
        if ($t eq 'tree_val' && @$kids == 1) { $id = $kids->[0]; next }
        return 0;
      }
      return 1 if ref($node) eq 'PPI::Token::Operator' && @$kids
                  && $SCALAR_ROOT_OP{ $node->content };
      return 1 if ref($node) && $node->isa('PPI::Token::Number');
      return 1 if ref($node) && $node->isa('PPI::Token::Quote');
      return 1 if ref($node) eq 'PPI::Token::Symbol' && !@$kids
                  && $node->content =~ /^\$\w+$/;
      return 0;
    }
  };
  return $ok ? 1 : 0;
}

# ---------------------------------------------------------------- small helpers

sub _strip_semi {
  return grep { !($_->isa('PPI::Token::Structure') && $_->content eq ';') } @_;
}

# Split "EXPR if COND" style trailing statement modifiers at the top level.
sub _split_modifier {
  my ($parts) = @_;
  for my $i (1 .. $#$parts) {
    my $p = $parts->[$i];
    if ($p->isa('PPI::Token::Word') && $p->content =~ /^(if|unless|while|until|for|foreach)$/) {
      return ([@$parts[0 .. $i - 1]], $p->content, [@$parts[$i + 1 .. $#$parts]]);
    }
  }
  return ($parts, undef, undef);
}

sub _apply_modifier {
  my ($form, $mod, $cond, $self, $stmt) = @_;
  return $form unless $mod;
  my $condform = $self->_lower_expr($cond, $stmt);
  return ['p-if', $condform, $form]          if $mod eq 'if';
  return ['p-if', ['p-!', $condform], $form] if $mod eq 'unless';
  die "Parser2 TODO: statement modifier '$mod'";
}

# `my $x` / `my $x = INIT` → ($name, \@init_parts | undef); else ().
sub _single_scalar_decl {
  my ($self, $stmt) = @_;
  my @k = _strip_semi($stmt->schildren);
  return () unless @k >= 2
    && $k[0]->isa('PPI::Token::Word') && $k[0]->content eq 'my'
    && $k[1]->isa('PPI::Token::Symbol') && $k[1]->content =~ /^\$\w+$/;
  my $name = $k[1]->content;
  return ($name, undef) if @k == 2;
  return () unless $k[2]->isa('PPI::Token::Operator') && $k[2]->content eq '=';
  return ($name, [@k[3 .. $#k]]);
}

sub _cond_parts {
  my ($cond) = @_;
  return map { $_->schildren } grep { $_->isa('PPI::Statement') } $cond->children;
}

1;
