package Pl::Parser2;

# Parser2 (prototype) — the v2 statement-level pipeline: structured emission
# (Pl::CLForm) instead of an interleaved text stream.  SAME external API as
# Pl::Parser (parse_file / parse_code / parse → CL text with the
# "(in-package :pcl)" marker pl2cl rewrites), so the two pipelines are
# switchable: pl2cl picks this class when PCL_V2=1.
#
# Division of labour while v2 is being written:
#   - statement/scope/sub STRUCTURE is lowered natively to forms here —
#     nested `let`s at declaration sites (scoping by construction), real
#     lambda lists for `my (LIST) = @_` subs, no VOID `*wantarray*` wraps,
#     VarAnnotator-gated unboxed scalars;
#   - every EXPRESSION is first offered to Pl::ExprToCL2 (strict native
#     subset), and otherwise generated by the ORIGINAL machinery — a real
#     Pl::Parser instance (`fallback_parser`) whose `_parse_expression`
#     reuses PExpr + ExprToCL unchanged; its output embeds as a CLForm raw.
#
# Prototype boundary: unsupported statement kinds die with "Parser2 TODO:".

use v5.30;
use strict;
use warnings;
use Moo;
use PPI;
use Pl::Parser;
use Pl::Environment;
use Pl::PExpr;
use Pl::ExprToCL2;
use Pl::VarAnnotator;
use Pl::CLForm qw(raw raw_wrap);

has filename => (is => 'ro', predicate => 1);
has code     => (is => 'ro', predicate => 1);

# Pre-pass result, keyed by package: { pkg => { perl sub name →
# { cl_name, insensitive } } } (see ExprToCL2).  Bareword sub resolution is
# package-scoped in Perl, so ExprToCL2/VarAnnotator only ever see the CURRENT
# package's slice (_cur_sub_info).
has sub_info => (is => 'rw', default => sub { {} });

# Package of the segment currently being lowered (see parse()'s segment split).
has cur_pkg => (is => 'rw', default => 'main');

sub _cur_sub_info {
  my $self = shift;
  return $self->sub_info->{ $self->cur_pkg } //= {};
}

has environment => (is => 'lazy');
sub _build_environment {
  my $self = shift;
  return Pl::Environment->new(
    source_file => $self->has_filename ? $self->filename : '-');
}

# The original parser, used purely as the expression-codegen engine.
has fallback_parser => (is => 'lazy');
sub _build_fallback_parser {
  my $self = shift;
  my $p = Pl::Parser->new(
    ($self->has_filename ? (filename => $self->filename) : ()),
    ($self->has_code     ? (code     => $self->code)     : ()),
    environment => $self->environment,
  );
  # Minimal live state _parse_expression's helpers expect (mirrors parse()).
  $p->_sections([]);
  $p->_cur_bucket('runtime');
  $p->_open_section('pcl');
  $p->{_let_bound_vars} = {};
  return $p;
}

sub parse_file { my ($class, $fn, %opts) = @_; return $class->new(filename => $fn)->parse }
sub parse_code { my ($class, $code, %opts) = @_; return $class->new(code => $code)->parse }

sub _source {
  my $self = shift;
  return $self->code if $self->has_code;
  open my $fh, '<', $self->filename or die "Parser2: cannot read " . $self->filename . ": $!";
  local $/;
  return scalar <$fh>;
}

sub parse {
  my $self = shift;
  my $src = Pl::Parser::_preprocess_source(Pl::Parser::_maybe_decode_utf8($self->_source));
  # String eval (eval EXPR, not eval BLOCK) captures enclosing my-lexicals via
  # dynamic lookup (session-250 mechanism) — that requires the v1 shape where
  # file-scope my-vars are defvar'd specials.  v2's true lexical `let`s are
  # invisible to separately-compiled eval'd code, so any such file → v1.
  # (Conservative: also triggers on `eval` in comments/strings.)
  die "Parser2 TODO: string eval (needs special-var my capture)\n"
    if $src =~ /\beval\b(?!\s*\{)/;
  my $doc = PPI::Document->new(\$src) or die "Parser2: PPI parse failed";
  $self->environment->package_stack(['main']);
  $self->environment->state_var_renames({});
  $self->{_referenced_pkgs} = {};

  # ---- Split the top level into PACKAGE SEGMENTS at statement-form
  # `package Foo;`.  v2 mirrors v1's section model: each segment becomes its
  # own output section whose (in-package …) preamble puts the READER in the
  # right CL package — an in-package nested inside a form is a no-op for the
  # rest of that already-read form, so the switch must happen between
  # top-level forms.  Block form / versioned `package` stay TODO (whole-file
  # v1 fallback); `package` inside a block dies in _lower_stmt.
  my @segments = ({ pkg => 'main', stmts => [] });
  for my $child ($doc->schildren) {
    if ($child->isa('PPI::Statement::Package')) {
      die "Parser2 TODO: package block form\n"
        if grep { $_->isa('PPI::Structure::Block') } $child->schildren;
      die "Parser2 TODO: package with version\n" if eval { $child->version };
      push @segments, { pkg => ($child->namespace // 'main'), stmts => [] };
      next;
    }
    push @{ $segments[-1]{stmts} }, $child;
  }
  $self->_check_my_spanning(\@segments) if @segments > 1;

  # Pre-pass: collect per-sub facts BEFORE lowering anything, so call sites
  # that precede (or recurse into) a sub's definition see them.  Register each
  # sub in the SHARED Environment too — the fallback expression machinery
  # decides bareword-vs-string ("foo" vs (pl-foo)) from declared_subs, and
  # Parser2 never runs v1's _process_sub_statement which normally does this.
  # Keyed by the segment's package: `sub hi` after `package Foo;` is Foo::hi.
  for my $seg (@segments) {
    $self->_set_cur_package($seg->{pkg});
    for my $child (@{ $seg->{stmts} }) {
      # Named subs anywhere in the statement — top-level or nested inside a
      # block (Perl subs are package-global regardless of nesting; the nested
      # ones hoist via _hoist_nested_sub during lowering).
      # NB: PPI::Statement::Scheduled (BEGIN/END/…) ISA Statement::Sub — those
      # are runnable blocks, not sub definitions; they lower via _fallback_stmt.
      # NB2: PPI find returns 0 (not undef) when nothing matches → `|| []`.
      my @subs = $child->isa('PPI::Statement::Sub')
        ? ($child)
        : @{ $child->find('PPI::Statement::Sub') || [] };
      for my $sub (@subs) {
        next unless $sub->name && $sub->block
          && !$sub->isa('PPI::Statement::Scheduled');
        # A prototype/signature changes how CALL SITES parse (arity, imposed
        # context) — outside the prototype's native subset.
        die "Parser2 TODO: sub with prototype/signature: " . $sub->name
          if $sub->prototype;
        # cl_name stays UNQUALIFIED (pl-foo) for a plain name: the section's
        # in-package makes the reader intern it in the segment's package —
        # exactly v1's per-section convention.
        $self->sub_info->{ $seg->{pkg} }{ $sub->name } = {
          cl_name     => $self->fallback_parser->_qualified_sub_to_cl($sub->name),
          insensitive => $self->_sub_ctx_insensitive($sub),
        };
        $self->environment->add_declared_sub($sub->name, $seg->{pkg});
        # Same default signature v1's _process_sub_statement registers for a
        # prototype-less sub: PExpr consults get_prototype() to decide that a
        # bareword `foo` is a CALL (pl-foo), not the string "foo".
        $self->environment->add_prototype($sub->name,
                                          { params => [], min_params => -1, is_proto => 0 });
      }
    }
  }

  # ---- Lower each segment into a section record.
  my @sections;
  for my $seg (@segments) {
    $self->_check_sub_captures($seg->{stmts});
    $self->cur_pkg($seg->{pkg});
    $self->_set_cur_package($seg->{pkg});
    $self->{_captured_decls} = [];
    $self->{_hoisted_decls}  = [];
    $self->{_hoisted_defs}   = [];
    $self->{_live_lex}       = {};
    my (@decls, @defs, @top);
    for my $child (@{ $seg->{stmts} }) {
      if ($child->isa('PPI::Statement::Sub') && $child->name
          && !$child->isa('PPI::Statement::Scheduled')) {
        push @decls, ['p-declare-sub', $self->fallback_parser->_qualified_sub_to_cl($child->name)];
        push @defs, $self->_lower_sub($child);
        next;
      }
      # `use strict`-family pragmas are pure no-ops; real use/require/BEGIN
      # statements stay IN the statement stream (position matters: a module
      # must load before the code that follows it runs) and lower through the
      # statement fallback in _lower_block.
      next if $child->isa('PPI::Statement::Null');
      push @top, $child;
    }
    my @runtime = $self->_lower_block(\@top, Pl::VarAnnotator->analyze(\@top, undef, $self->_cur_sub_info));
    # Named subs found nested inside blocks during lowering (package-global
    # in Perl) hoist into the same decl/def buckets as top-level subs.
    push @decls, @{ $self->{_hoisted_decls} };
    push @defs,  @{ $self->{_hoisted_defs} };
    push @sections, {
      pkg      => $seg->{pkg},
      decls    => [map { Pl::CLForm::to_string($_, 0) } @decls],
      defs     => [map { Pl::CLForm::to_string($_, 0) } @defs],
      run      => [map { Pl::CLForm::to_string($_, 0) } @runtime],
      captured => [@{ $self->{_captured_decls} }],
    };
  }

  # ---- Assemble the sections.
  my @body;
  for my $i (0 .. $#sections) {
    my $sec = $sections[$i];
    my $pkg = $sec->{pkg};
    my $cl_pkg = $self->fallback_parser->_cl_pkg_designator($pkg);
    if ($i > 0) {
      # v1's package-section preamble: create/enter the CL package, CLOS
      # class for MRO, original-case registration, per-package $a/$b
      # specials (sort comparator lambdas bind them dynamically).
      my $cl_class = $self->fallback_parser->_pkg_to_clos_class($pkg);
      push @body, ";;; package $pkg",
                  "(p-defpackage $cl_pkg)",
                  "(in-package $cl_pkg)",
                  "(defclass $cl_class () ())",
                  "(p-register-pkg-name $cl_pkg \"$pkg\")", '';
    }
    push @body, @{ $sec->{decls} };
    push @body, '(defvar $a (make-p-box nil))', '(defvar $b (make-p-box nil))', '';
    # Undeclared package globals referenced in this section (v1's forward-
    # declaration pass) — defvar'd so first use isn't an unbound-variable
    # crash.  Per-section: the same unqualified $x names DIFFERENT vars in
    # different packages, and the defvar must be read under this section's
    # in-package.
    push @body, $self->_forward_global_decls(join("\n", @{ $sec->{captured} },
                                                        @{ $sec->{defs} },
                                                        @{ $sec->{run} })), '';
    # Declarations captured by _fallback_stmt during lowering (defvar/
    # defconstant/eval-when from use/require/BEGIN) — before the definitions
    # that may reference them.
    push @body, @{ $sec->{captured} }, '';
    push @body, map { ($_, '') } @{ $sec->{defs} };
    # Runtime current-package tracking (caller()/__PACKAGE__) in execution
    # order — after this section's definitions load, before its code runs.
    push @body, "(p-set-current-package $cl_pkg \"$pkg\")", '' if $i > 0;
    push @body, map { ($_, '') } @{ $sec->{run} };
  }

  my @out = ('(in-package :pcl)', '');
  # Pre-declare every package a later section opens or a qualified symbol
  # references: load reads+evaluates one top-level form at a time, so a
  # p-defpackage up top guarantees Pkg::sym forms further down are readable.
  my %pre = map { ($_->{pkg} => 1) } @sections[1 .. $#sections];
  $pre{$_} = 1 for keys %{ $self->{_referenced_pkgs} };
  # Packages referenced via qualified CALLS (PerlIO::get_layers($fh)) register
  # in the shared Environment as the fallback expressions parse — v1 pre-
  # declares these the same way (get_undeclared_packages).
  $pre{$_} = 1 for @{ $self->environment->get_undeclared_packages() };
  delete @pre{qw(main pcl)};
  push @out, map { "(pcl:p-defpackage " . $self->fallback_parser->_cl_pkg_designator($_) . ")" }
             sort keys %pre;
  push @out, '' if %pre;
  push @out, @body;
  return join("\n", @out);
}

# Reset the shared Environment's notion of the current package to a segment's
# package (v1's statement-form `package` pushes with no pop — same effect).
sub _set_cur_package {
  my ($self, $pkg) = @_;
  $self->environment->package_stack(['main']);
  return if $pkg eq 'main';
  $self->environment->push_package($pkg);
  $self->environment->add_package($pkg);
}

# v2 `let`s CLOSE at a package boundary (each segment is its own top-level
# section), but Perl file lexicals stay in scope across `package`.  A my-name
# from an earlier segment mentioned in a later one → die → whole-file v1
# fallback (v1's file-scope my-vars are defvar'd specials, which DO span
# sections).  Text-scan conservative: a redeclaration of the same name or a
# mention in a comment also dies — that only costs the v2 lowering, never
# correctness.
sub _check_my_spanning {
  my ($self, $segments) = @_;
  my %live;   # bare names (no sigil) of my-vars declared in earlier segments
  for my $i (0 .. $#$segments) {
    if ($i && %live) {
      my $txt = join "\n", map { $_->content } @{ $segments->[$i]{stmts} };
      for my $bare (sort keys %live) {
        die "Parser2 TODO: my-lexical '$bare' spans a package boundary\n"
          if $txt =~ /(?:[\$\@\%]|\$\#)\Q$bare\E\b/;
      }
    }
    $self->_collect_lexical_names($segments->[$i]{stmts}, \%live);
  }
}

# Bare names (sigil stripped) of my/state-declared vars among the given
# TOP-LEVEL statements, added to %$live.  `our`/`local` are skipped — they
# name package vars, which resolve per-package.
sub _collect_lexical_names {
  my ($self, $stmts, $live) = @_;
  for my $stmt (@$stmts) {
    next unless ref $stmt && $stmt->isa('PPI::Statement::Variable');
    my $kw = ($stmt->schildren)[0];
    next unless $kw && $kw->isa('PPI::Token::Word') && $kw->content =~ /^(?:my|state)$/;
    my ($n)    = $self->_single_scalar_decl($stmt);
    my ($vars) = $self->_multi_decl($stmt);
    if ($n)        { $live->{ substr($n, 1) } = 1 }
    elsif ($vars)  { $live->{ substr($_, 1) } = 1 for @$vars }
    else {
      # Unrecognized declaration shape — take every symbol conservatively.
      my $syms = $stmt->find('PPI::Token::Symbol') || [];
      $live->{ substr($_->content, 1) } = 1
        for grep { $_->content =~ /^[\$\@\%]\w+$/ } @$syms;
    }
  }
}

# Named top-level subs are HOISTED into the definitions bucket, OUTSIDE the
# nested `let`s that bind the file's my-lexicals — a sub body that captures
# one would compile a free (→ unbound) symbol.  v1 defvar's file lexicals, so
# the capture works there → die → whole-file v1 fallback.  (Anonymous subs
# are fine: they are lowered in place, inside the lets.)  Conservative text
# scan: a sub that re-declares the same name with its own `my` also dies —
# that only costs the v2 lowering, never correctness.
sub _check_sub_captures {
  my ($self, $stmts) = @_;
  my %lex;
  $self->_collect_lexical_names($stmts, \%lex);
  return unless %lex;
  for my $child (@$stmts) {
    next unless $child->isa('PPI::Statement::Sub') && $child->name && $child->block
      && !$child->isa('PPI::Statement::Scheduled');
    my $txt = $child->block->content;
    for my $bare (sort keys %lex) {
      die "Parser2 TODO: file lexical '$bare' captured by sub " . $child->name . "\n"
        if $txt =~ /(?:[\$\@\%]|\$\#)\Q$bare\E\b/;
    }
  }
}

# v2 twin of v1's _insert_variable_forward_declarations, with the key v2
# difference: any name Parser2 let-binds is a TRUE lexical and must NOT be
# defvar'd (proclaiming it special would poison every let of that name —
# closures would capture the symbol, raw slots would break).  So: defvar
# exactly the referenced sigil-vars that are neither let-bound anywhere in
# the file nor runtime-owned.
sub _forward_global_decls {
  my ($self, $text) = @_;
  my %runtime_vars = map { $_ => 1 } qw($_ @_ %_args @ARGV @INC %ENV %INC %SIG
                                        $a $b @a @b);
  my $lb = $self->fallback_parser->{_let_bound_vars} // {};
  my %skip_pkg = map { $_ => 1 } qw(ENV INC SIG pcl);
  my (%seen, %cross);
  for my $line (split /\n/, $text) {
    next if $line =~ /^\s*;;/;
    next if $line =~ /^\s*\(defvar\s/;
    # (?<![\w:|]) skips pkg-qualified Foo::$x / |P|::$x; (?!-) skips runtime
    # internals like %pcl-cl-sub-name.
    while ($line =~ /(?<![\w:|])([\$\@\%][A-Za-z_]\w*)(?!-)/g) {
      my $v = $1;
      next if $runtime_vars{$v} || $lb->{$v};
      $seen{$v} = 1;
    }
    # Cross-package refs (main::$IS_ASCII from a required harness, Foo::@bar)
    # get a defvar in THEIR package — v1's %cross_pkg_vars behaviour.
    while ($line =~ /(?:\b([a-zA-Z_]\w*)|\|([^|]+)\|)::([\$\@\%][A-Za-z_]\w*)(?!-)/g) {
      my ($pkg, $var) = (defined($1) ? $1 : "|$2|", $3);
      next if $skip_pkg{ defined($1) ? $1 : $2 };
      # Referenced packages must exist when the qualified symbol is READ —
      # parse() pre-declares them at the top of the file.
      $self->{_referenced_pkgs}{ defined($1) ? $1 : $2 } = 1;
      next if $pkg eq 'main' && $runtime_vars{$var};
      $cross{"$pkg\::$var"} = 1;
    }
  }
  return () unless %seen || %cross;
  my @decls = (';; Forward declarations for undeclared package globals');
  for my $v (sort keys %seen) {
    push @decls, "(defvar $v " . _fresh_container($v) . ")";
  }
  for my $qv (sort keys %cross) {
    (my $var = $qv) =~ s/^.*:://;
    push @decls, "(defvar $qv " . _fresh_container($var) . ")";
  }
  return @decls;
}

# ---------------------------------------------------------------- subs

# The shared Environment's in_subroutine counter drives fallback-expression
# decisions (bare shift/pop default to @_ inside a sub, @ARGV at top level;
# my-var qualification; the top-level notinline guard) — v1 bumps it around
# sub bodies, so v2 must too.
sub _lower_sub {
  my ($self, $sub) = @_;
  my $env = $self->environment;
  $env->in_subroutine($env->in_subroutine + 1);
  my %saved_lex = %{ $self->{_live_lex} // {} };
  my $form = eval { $self->_lower_sub_inner($sub) };
  my $err = $@;
  $self->{_live_lex} = \%saved_lex;
  $env->in_subroutine($env->in_subroutine - 1);
  die $err if $err;
  return $form;
}

sub _lower_sub_inner {
  my ($self, $sub) = @_;
  my $clname = $self->fallback_parser->_qualified_sub_to_cl($sub->name);
  my @stmts = $sub->block->schildren;

  my $params = $self->_extract_params($stmts[0]);
  my @body_stmts = @stmts;
  shift @body_stmts if $params;
  $self->_reg_lex(@{ $params // [] });

  if ($params) {
    my $rest_txt = join("\n", map { $_->content } @body_stmts);
    my $body_uses_args = $rest_txt =~ /\@_|\$_\[|\bshift\b|\bgoto\b|\bwantarray\b/;
    my $vi = Pl::VarAnnotator->analyze(\@body_stmts, $params, $self->_cur_sub_info);
    if (!$body_uses_args && !grep { !$vi->{$_}{unboxable} } @$params) {
      # Real lambda list (#3): my ($a,$b) = @_ untouched afterwards, params
      # never written un-arithmetically / ref-taken → bind raw, no p-list-=.
      # The body provably never reads @_, so skip the p-args-body prologue
      # (no p-flatten-args per call) and stack-allocate the unused &rest.
      my $ll = ['list', '&optional',
                (map { ['list', $_, '(p-undef)'] } @$params),
                '&rest', '%_args'];
      return ['p-sub', $clname, $ll,
              raw('(declare (ignore %_args) (dynamic-extent %_args))'),
              ['block', 'nil', $self->_lower_block(\@body_stmts, $vi, 'inherit')]];
    }
    # Old convention with boxed params + synthesized list-assign binding.
    $vi->{$_} = { unboxable => 0 } for @$params;
    return ['p-sub', $clname, ['list', '&rest', '%_args'],
            ['p-args-body', ['block', 'nil',
              ['let', ['list', map { ['list', $_, '(make-p-box nil)'] } @$params],
                raw('(let ((*wantarray* nil)) (p-list-= (vector ' . join(' ', @$params) . ') @_))'),
                $self->_lower_block(\@body_stmts, $vi, 'inherit')]]]];
  }

  my $vi = Pl::VarAnnotator->analyze(\@stmts, undef, $self->_cur_sub_info);
  return ['p-sub', $clname, ['list', '&rest', '%_args'],
          ['p-args-body', ['block', 'nil', $self->_lower_block(\@stmts, $vi, 'inherit')]]];
}

# Register a `my`-declared name: for the fallback machinery's my-vs-package
# decisions (`_let_bound_vars`, never shrinks — mirrors v1's accumulator) and
# for the LIVE lexical-scope set (`_live_lex`, restored at scope exit by
# _lower_scope/_lower_sub) that the nested-sub capture check reads.
sub _reg_lex {
  my ($self, @names) = @_;
  for my $n (@names) {
    $self->fallback_parser->{_let_bound_vars}{$n} = 1;
    $self->{_live_lex}{$n} = 1;
  }
  return;
}

# Lower a Structure::Block's statements: a lexical scope — names declared
# inside stop being "live" when it closes.
sub _lower_scope {
  my ($self, $stmts, $vi, $tail_ctx) = @_;
  my %saved = %{ $self->{_live_lex} // {} };
  my @forms = $self->_lower_block($stmts, $vi, $tail_ctx);
  $self->{_live_lex} = \%saved;
  return @forms;
}

# A named sub nested inside a block hoists to the section's definitions
# bucket, OUTSIDE any lexical `let`s — safe only when its body provably
# references no lexical LIVE at this point (a real capture, e.g. the
# `{ my $x = 0; sub X::DESTROY { $x++ } }` static-variable idiom, must fall
# back to v1, whose defvar'd my-vars make the capture work).  Conservative
# text scan; over-firing only costs the v2 lowering, never correctness.
sub _hoist_nested_sub {
  my ($self, $sub) = @_;
  my $txt = $sub->block->content;
  for my $var (sort keys %{ $self->{_live_lex} // {} }) {
    (my $bare = $var) =~ s/^[\$\@\%]//;
    die "Parser2 TODO: lexical '$bare' possibly captured by nested sub " . $sub->name . "\n"
      if $txt =~ /(?:[\$\@\%]|\$\#)\Q$bare\E\b/;
  }
  push @{ $self->{_hoisted_decls} },
    ['p-declare-sub', $self->fallback_parser->_qualified_sub_to_cl($sub->name)];
  push @{ $self->{_hoisted_defs} }, $self->_lower_sub($sub);
  return;
}

# `my ($a, $b) = @_;` → ['$a','$b'] | undef
sub _extract_params {
  my ($self, $stmt) = @_;
  return undef unless $stmt && $stmt->isa('PPI::Statement::Variable');
  my @k = $stmt->schildren;
  return undef unless @k >= 4
    && $k[0]->content eq 'my'
    && $k[1]->isa('PPI::Structure::List')
    && $k[2]->isa('PPI::Token::Operator') && $k[2]->content eq '='
    && $k[3]->isa('PPI::Token::Magic') && $k[3]->content eq '@_';
  my @params = map { $_->content }
               grep { $_->isa('PPI::Token::Symbol') }
               map { $_->tokens } $k[1];
  return undef unless @params && !grep { !/^\$\w+$/ } @params;
  return \@params;
}

# ---------------------------------------------------------------- blocks

# Lower a statement list to forms.  A `my` declaration NESTS the remainder of
# the block inside its `let` — scoping is a property of the tree, never of
# emitted text (the R3 fix).
#
# $tail_ctx: context of the block's LAST statement value.  A sub body passes
# 'inherit' (its tail is the sub's return value, so a tail call must see the
# CALLER's *wantarray*); everything else leaves it undef → statement position
# is void.  Threaded through `my`-let nesting and tail if/unless branches.
sub _lower_block {
  # One recursion level PER STATEMENT (each `my` nests the block remainder):
  # a few hundred top-level statements is normal, not runaway recursion.
  no warnings 'recursion';
  my ($self, $stmts, $vi, $tail_ctx) = @_;
  my @s = grep { ref $_ && !$_->isa('PPI::Statement::Null') } @$stmts;
  return () unless @s;
  my ($first, @rest) = @s;
  my $first_tail = @rest ? undef : $tail_ctx;

  # -- local …;  → v1's local machinery via the fallback seam; the opened
  # save/restore scope wraps the lowered block remainder (see _lower_local).
  # Standalone `delete local $h{k};` is a plain PPI::Statement with the same
  # scope-to-block-end behaviour — same route.
  if ($self->_is_local_stmt($first)) {
    return $self->_lower_local($first, \@rest, $vi, $tail_ctx);
  }

  # -- my $x [= INIT];  → (let (($x …)) rest...)
  if ($first->isa('PPI::Statement::Variable')) {
    my $our = $self->_lower_our_decl($first);
    return (@$our, $self->_lower_block(\@rest, $vi, $tail_ctx)) if $our;
    my ($name, $init) = $self->_single_scalar_decl($first);
    if ($name) {
      $self->_reg_lex($name);
      if ($vi->{$name} && $vi->{$name}{unboxable}) {
        my $initform = defined $init ? $self->_lower_expr($init, $first) : '(p-undef)';
        return (['let', ['list', ['list', $name, $initform]],
                 $self->_lower_block(\@rest, $vi, $tail_ctx)]);
      }
      return (['let', ['list', ['list', $name, '(make-p-box nil)']],
               (defined $init ? (['p-my-=', $name, $self->_lower_expr($init, $first)]) : ()),
               $self->_lower_block(\@rest, $vi, $tail_ctx)]);
    }
    # -- my @a / my %h / my (LIST) [= INIT];  → fresh containers in a let,
    # the assignment lowered by the ORIGINAL expression machinery (v1 parses
    # the whole `my … = …` statement as an expression and produces the
    # p-array-= / p-hash-= / p-list-= form — same path as Parser.pm's
    # _process_variable_statement).  All these vars stay boxed/containers.
    my ($vars, $has_init) = $self->_multi_decl($first);
    die "Parser2 TODO: unsupported declaration: " . $first->content unless $vars;
    my @k = _strip_semi($first->schildren);
    if ($has_init) {
      # Self-referential init (`my @a = (@a, 1)` — RHS must see the OUTER
      # var) needs v1's init-in-binding dance; out of the prototype subset.
      my ($eq_i) = grep { $k[$_]->isa('PPI::Token::Operator') && $k[$_]->content eq '=' } 0 .. $#k;
      my $rhs_txt = join ' ', map { $_->content } @k[$eq_i + 1 .. $#k];
      for my $v (@$vars) {
        die "Parser2 TODO: self-referential init: " . $first->content
          if $rhs_txt =~ /\Q$v\E\b/;
      }
    }
    $self->_reg_lex(@$vars);
    my @binds = map { ['list', $_, _fresh_container($_)] } @$vars;
    return (['let', ['list', @binds],
             ($has_init ? ($self->_lower_expr([@k], $first)) : ()),
             $self->_lower_block(\@rest, $vi, $tail_ctx)]);
  }

  # -- use/require/no, BEGIN/END blocks, __END__/__DATA__: whole-statement
  # fallback through the ORIGINAL parser (declarations hoisted to file top).
  if ($first->isa('PPI::Statement::Include')
      || $first->isa('PPI::Statement::Scheduled')
      || $first->isa('PPI::Statement::End')
      || $first->isa('PPI::Statement::Data')) {
    return ($self->_fallback_stmt($first), $self->_lower_block(\@rest, $vi, $tail_ctx));
  }

  # -- a named sub nested inside a block: package-global in Perl (the block
  # only bounds lexical capture, which _hoist_nested_sub gates on) — hoist
  # the definition into the section's decl/def buckets.
  if ($first->isa('PPI::Statement::Sub') && $first->name && $first->block) {
    $self->_hoist_nested_sub($first);
    return $self->_lower_block(\@rest, $vi, $tail_ctx);
  }

  # -- everything else appends a form and continues at the same depth.
  return ($self->_lower_stmt($first, $vi, $first_tail), $self->_lower_block(\@rest, $vi, $tail_ctx));
}

sub _lower_stmt {
  my ($self, $stmt, $vi, $tail_ctx) = @_;

  if ($stmt->isa('PPI::Statement::Compound')) {
    return $self->_lower_compound($stmt, $vi, $tail_ctx);
  }

  if ($stmt->isa('PPI::Statement::Break')) {
    my @k = _strip_semi($stmt->schildren);
    my $kw = $k[0]->content;
    if ($kw eq 'return') {
      shift @k;
      my ($expr, $mod, $cond) = _split_modifier(\@k);
      return $self->_fallback_stmt($stmt) if _modifier_needs_fallback($mod);
      # A returned call must see the CALLER's context (no *wantarray* bind).
      my $form = @$expr
        ? ['p-return', $self->_lower_expr($expr, $stmt, 'inherit')]
        : ['p-return', '(p-undef)'];
      return _apply_modifier($form, $mod, $cond, $self, $stmt);
    }
    # goto/next/last/redo: keep the keyword and let the ORIGINAL expression
    # machinery lower the whole thing (goto &sub tail-calls with the LIVE @_;
    # the $body_uses_args gate in _lower_sub has already kept the @_ binding
    # for any sub whose body mentions goto, so the forwarded @_ exists).
    my ($expr, $mod, $cond) = _split_modifier(\@k);
    return $self->_fallback_stmt($stmt) if _modifier_needs_fallback($mod);
    my $form = $self->_lower_expr($expr, $stmt);
    return _apply_modifier($form, $mod, $cond, $self, $stmt);
  }

  if ($stmt->isa('PPI::Statement::Scheduled') || $stmt->isa('PPI::Statement::Package')) {
    die "Parser2 TODO: " . ref($stmt);
  }

  # -- plain expression statement
  my @k = _strip_semi($stmt->schildren);
  my ($expr, $mod, $cond) = _split_modifier(\@k);
  # while/until/for/foreach statement modifiers (and do{}while, which splits
  # the same way) are outside the native subset — whole-statement fallback
  # through v1, which owns their loop/do-while semantics.
  return $self->_fallback_stmt($stmt) if _modifier_needs_fallback($mod);

  # `$x = RHS;` on a let-bound scalar → native form: `setf` when $x is a raw
  # (unboxed) slot — RHS proven arithmetic by VarAnnotator, so the stored
  # value is a raw number — else `p-my-=` (box-set; never the special-
  # proclaiming p-scalar-=).
  if (!$mod && @$expr >= 3
      && $expr->[0]->isa('PPI::Token::Symbol') && $expr->[0]->content =~ /^\$\w+$/
      && $expr->[1]->isa('PPI::Token::Operator') && $expr->[1]->content eq '=') {
    my $name = $expr->[0]->content;
    my $rhs = [@$expr[2 .. $#$expr]];
    if ($vi->{$name} && $vi->{$name}{unboxable}) {
      return ['setf', $name, $self->_lower_expr($rhs, $stmt)];
    }
    if ($self->fallback_parser->{_let_bound_vars}{$name}) {
      return ['p-my-=', $name, $self->_lower_expr($rhs, $stmt)];
    }
  }

  # Statement position: the value is discarded (void) — except for a block
  # tail whose value the enclosing sub returns ($tail_ctx = 'inherit').
  my $form = $self->_lower_expr($expr, $stmt, $tail_ctx // ':void');
  return _apply_modifier($form, $mod, $cond, $self, $stmt);
}

sub _lower_compound {
  my ($self, $stmt, $vi, $tail_ctx) = @_;
  my @k = $stmt->schildren;

  # Optional leading `LABEL:` — rides along on loops (`OUTER: while …`) and
  # bare blocks (`SKIP: { … }`).  Standalone labels (goto targets) and
  # labeled if/unless stay TODO → v1.
  my $label;
  if (@k && $k[0]->isa('PPI::Token::Label')) {
    ($label = (shift @k)->content) =~ s/\s*:$//;
  }
  die "Parser2 TODO: standalone label\n" unless @k;

  # Bare block { … } = a loop-once: last/next/redo all work inside it.
  if ($k[0]->isa('PPI::Structure::Block')) {
    die "Parser2 TODO: loop with continue block\n"
      if grep { $_->isa('PPI::Token::Word') && $_->content eq 'continue' } @k;
    # PPI mis-tokenizes an anon-hash constructor statement `{ LITERAL , … };`
    # as a bare block — v1's detector + statement fallback handle it.
    return $self->_fallback_stmt($stmt)
      if Pl::Parser::_bare_block_is_anon_hash($k[0]);
    return $self->_lower_bare_block($k[0], $label, $vi);
  }

  my $kw = $k[0]->content;
  die "Parser2 TODO: label on non-loop compound '$kw'\n"
    if defined $label && $kw !~ /^(?:while|until|for|foreach)$/;

  if ($kw eq 'if' || $kw eq 'unless') {
    # Collect (keyword, condition, block) clauses: if/unless, elsif*, else?.
    my (@clauses, $cur_kw, $cur_cond);
    for my $el (@k) {
      if    ($el->isa('PPI::Token::Word'))            { $cur_kw = $el->content }
      elsif ($el->isa('PPI::Structure::Condition'))   { $cur_cond = $el }
      elsif ($el->isa('PPI::Structure::Block')) {
        push @clauses, { kw => $cur_kw, cond => $cur_cond, block => $el };
        $cur_cond = undef;
      }
    }
    # Build nested p-if forms from the tail (else innermost) outward.
    # A tail if/unless is the enclosing block's VALUE — its branch blocks
    # inherit $tail_ctx (loop/plain compounds don't propagate values).
    my $form;
    if (@clauses && $clauses[-1]{kw} eq 'else') {
      my $c = pop @clauses;
      $form = ['progn', $self->_lower_scope([$c->{block}->schildren], $vi, $tail_ctx)];
    }
    while (my $c = pop @clauses) {
      my $cond = $self->_lower_expr([_cond_parts($c->{cond})], $stmt);
      $cond = ['p-!', $cond] if $c->{kw} eq 'unless';
      $form = ['p-if', $cond,
               ['progn', $self->_lower_scope([$c->{block}->schildren], $vi, $tail_ctx)],
               (defined $form ? ($form) : ())];
    }
    return $form;
  }

  if ($kw eq 'while' || $kw eq 'until') {
    # `continue` blocks run between iterations (also after `next`) — v1's
    # p-while :continue plumbing owns that; not lowered natively yet.
    die "Parser2 TODO: loop with continue block\n"
      if grep { $_->isa('PPI::Token::Word') && $_->content eq 'continue' } @k;
    my ($cond_s) = grep { $_->isa('PPI::Structure::Condition') } @k;
    my ($block)  = grep { $_->isa('PPI::Structure::Block') } @k;
    my $cond = $self->_lower_expr([_cond_parts($cond_s)], $stmt);
    # Perl loop conditions whose value comes from each/readline/readdir/glob
    # terminate on *undef*, not false-but-defined ("0" line, each's index 0),
    # and a bare `<FH>` implicitly assigns to $_ — v1's _auto_defined_cond,
    # applied at the raw seam (native conds can't contain these calls).
    # v1 skips the rewrite for `until`, matching perl.
    $cond = $self->_auto_defined_raw($cond) if $kw eq 'while';
    $cond = ['p-!', $cond] if $kw eq 'until';
    return ['p-while', $cond, _label_keys($label),
            $self->_lower_scope([$block->schildren], $vi)];
  }

  if (($kw eq 'for' || $kw eq 'foreach')
      && (my ($for_s) = grep { $_->isa('PPI::Structure::For') } @k)) {
    # C-style for (INIT; COND; STEP) BLOCK.  Sections are POSITIONAL: an
    # empty one is a PPI::Statement::Null (`;`) placeholder, and trailing
    # empties are simply absent.  Empty init/step → no form; empty cond →
    # constant true (v1's _process_c_style_for defaults).
    my ($block) = grep { $_->isa('PPI::Structure::Block') } @k;
    my @sect = grep { $_->isa('PPI::Statement') } $for_s->children;
    die "Parser2 TODO: for(;;) with extra sections" if @sect > 3;
    my ($init_s, $cond_s, $step_s) =
      map { $_ && !$_->isa('PPI::Statement::Null') ? $_ : undef } @sect[0 .. 2];

    # A `my $i = INIT` init binds the counter in a let AROUND the p-for —
    # register the name BEFORE lowering cond/step/body so fallback expressions
    # see it as let-bound.  Unboxable (e.g. step `$i = $i + 1`) → raw slot;
    # else boxed (a `$i++` step keeps VarAnnotator conservative).
    my ($name, $init) = $init_s ? $self->_single_scalar_decl($init_s) : ();
    $self->_reg_lex($name) if $name;

    # ++-step carve-out: when the step is a PURE `$i++`/`++$i` (or --), the ++
    # is position-known — it IS the step slot, whose value is discarded — so
    # lower it as the equivalent `(setf $i (p-± $i 1))` and let the counter
    # unbox, provided a re-analysis of the loop WITHOUT the step (init, cond,
    # body — where the text-scan gates are trustworthy) approves the name.
    my $step_form;
    if ($name && $step_s && !($vi->{$name} && $vi->{$name}{unboxable})
        && (my $incr = _pure_incr_step($step_s, $name))) {
      my $vi2 = Pl::VarAnnotator->analyze(
        [(grep { defined } $init_s, $cond_s), $block->schildren],
        undef, $self->_cur_sub_info);
      if ($vi2->{$name} && $vi2->{$name}{unboxable}) {
        $vi = { %$vi, $name => { unboxable => 1 } };
        $step_form = ['list', ['setf', $name, ["p-$incr", $name, '1']]];
      }
    }

    my $cond = $cond_s
      ? ['list', $self->_auto_defined_raw(
                   $self->_lower_expr([_strip_semi($cond_s->schildren)], $stmt))]
      : ['list', 't'];
    my $step = $step_form
      // ($step_s ? ['list', $self->_lower_stmt($step_s, $vi)] : ['list']);
    my @body = $self->_lower_scope([$block->schildren], $vi);

    if ($name) {
      my $initval = defined $init ? $self->_lower_expr($init, $stmt) : '(p-undef)';
      if ($vi->{$name} && $vi->{$name}{unboxable}) {
        return ['let', ['list', ['list', $name, $initval]],
                ['p-for', ['list'], $cond, $step, _label_keys($label), @body]];
      }
      return ['let', ['list', ['list', $name, '(make-p-box nil)']],
              ['p-for', ['list', ['p-my-=', $name, $initval]], $cond, $step,
               _label_keys($label), @body]];
    }
    return ['p-for',
            ['list', ($init_s ? ($self->_lower_stmt($init_s, $vi)) : ())],
            $cond, $step, _label_keys($label), @body];
  }

  if ($kw eq 'for' || $kw eq 'foreach') {
    die "Parser2 TODO: loop with continue block\n"
      if grep { $_->isa('PPI::Token::Word') && $_->content eq 'continue' } @k;
    my ($list) = grep { $_->isa('PPI::Structure::List') } @k;
    my ($block) = grep { $_->isa('PPI::Structure::Block') } @k;
    my ($var) = grep { $_->isa('PPI::Token::Symbol') } @k;
    die "Parser2 TODO: foreach without list" unless $list && $block;
    my $name = $var ? $var->content : '$_';
    $self->_reg_lex($name);
    my @list_parts = map { $_->schildren } grep { $_->isa('PPI::Statement') } $list->children;
    return ['p-foreach', ['list', $name, $self->_lower_expr(\@list_parts, $stmt, 1)],
            _label_keys($label),
            $self->_lower_scope([$block->schildren], $vi)];
  }

  die "Parser2 TODO: compound '$kw'";
}

# `:label NAME` pair for the loop macros' parse-loop-keys (must come first in
# the body-and-keys tail), or nothing.
sub _label_keys {
  my ($label) = @_;
  return () unless defined $label;
  return (':label', $label);
}

# A bare block is a single-iteration loop: last/next/redo work inside it.
# The shapes replicate v1's _process_bare_block exactly — unlabeled uses the
# plain (block nil (tagbody :redo … :next)) that unlabeled p-last/p-next/
# p-redo target; labeled adds the LAST/NEXT/REDO catch tags that the
# *-dynamic throws (e.g. Test::More's skip() doing `last SKIP` from inside a
# called sub) unwind to.  The (let ((*package* *package*))) wrapper stops an
# (in-package …) reached inside the block (module loads via the statement
# fallback) from leaking to subsequent top-level forms.  `my` scoping needs
# no bookkeeping: _lower_block's nested lets sit inside the tagbody, and a
# (go …) legally jumps out of them.
sub _lower_bare_block {
  my ($self, $block, $label, $vi) = @_;
  my @body = $self->_lower_scope([$block->schildren], $vi);
  my $inner;
  if (defined $label) {
    $inner =
      ['block', $label,
        ['catch', "(pcl::%pcl-loop-tag \"LAST\" '$label)",
          ['catch', "(pcl::%pcl-loop-tag \"NEXT\" '$label)",
            ['tagbody', ':redo',
              ['catch', "(pcl::%pcl-loop-tag \"REDO\" '$label)",
                ['progn', @body, '(go :next)']],
              '(go :redo)',
              ':next']]]];
  } else {
    $inner = ['block', 'nil', ['tagbody', ':redo', @body, ':next']];
  }
  return ['let', ['list', ['list', '*package*', '*package*']], $inner];
}

# ---------------------------------------------------------------- expressions

# Native (ExprToCL2 strict subset) or the ORIGINAL expression pipeline.
# $ctx describes the expression's position:
#   undef → scalar; 1 → list (fallback list-parse: e.g. a foreach list
#   `2..$n` is a range, not a scalar flip-flop; native funcall bind t);
#   ':void' → statement position; 'inherit' → return/sub-tail (callee sees
#   the CALLER's *wantarray*).  The fallback only distinguishes scalar/list.
sub _lower_expr {
  my ($self, $parts, $stmt, $ctx) = @_;
  my @parts = _strip_semi(@$parts);
  die "Parser2: empty expression" unless @parts;

  my $native_ctx = !defined $ctx        ? undef
                 : "$ctx" eq '1'        ? 't'
                 :                        $ctx;
  my $native = eval {
    my $expr_o = Pl::PExpr->new(
      e           => \@parts,
      environment => $self->environment,
      parser      => $self->fallback_parser,
    );
    my ($node_id) = $expr_o->parse_expr_to_tree(\@parts);
    Pl::ExprToCL2->new(expr_o => $expr_o, environment => $self->environment,
                       sub_info => $self->_cur_sub_info)
                 ->gen_form($node_id, $native_ctx);
  };
  return $native if defined $native;

  my $fb_ctx = (defined $ctx && "$ctx" eq '1') ? 1 : 0;
  my $cl = $self->fallback_parser->_parse_expression(\@parts, $stmt, $fb_ctx);
  die "Parser2: expression fallback failed for: " . join(' ', map { $_->content } @parts)
    unless defined $cl;
  # Legacy-boundary parity: the old pipeline rewrites (p-scalar-= $x …) to
  # (p-my-= $x …) for let-bound names inside _emit, which the fallback path
  # bypasses.  Apply the same conversion at the raw boundary (v2-native
  # assignments never need this — they are lowered as p-my-=/setf forms).
  my $lb = $self->fallback_parser->{_let_bound_vars} // {};
  for my $var (keys %$lb) {
    my $pat = quotemeta("(p-scalar-= $var");
    $cl =~ s/$pat(?=[\s)])/(p-my-= $var/g;
  }
  return raw($cl);
}

# Apply v1's _auto_defined_cond to a loop condition that lowered through the
# fallback seam: `(p-scalar-= $x (p-each …))` → wrapped in (p-defined $x),
# bare `(p-readline …)` → `(progn (p-setf $_ …) (p-defined $_))`, etc.
# Native condition FORMS are returned untouched — the native subset cannot
# produce each/readline/readdir/glob calls, so only raw text needs it.
sub _auto_defined_raw {
  my ($self, $cond) = @_;
  return $cond unless Pl::CLForm::is_raw($cond);
  return raw($self->fallback_parser->_auto_defined_cond($$cond));
}

# ------------------------------------------------------- context sensitivity

# A sub is context-INSENSITIVE when its caller's *wantarray* provably cannot
# be observed: no `wantarray` in the body, and every value it can return —
# each explicit `return EXPR` and the implicit last-statement value — is
# scalar-shaped.  Conservative: any doubt → sensitive (call sites keep the
# dynamic bind, exactly today's behaviour).
sub _sub_ctx_insensitive {
  my ($self, $sub) = @_;
  my $txt = $sub->block->content;
  return 0 if $txt =~ /\bwantarray\b/;

  my $breaks = $sub->block->find('PPI::Statement::Break') || [];
  for my $b (@$breaks) {
    my @k = _strip_semi($b->schildren);
    my $kw = shift @k;
    next unless $kw && $kw->content eq 'return';
    return 0 unless @k;                        # bare `return;` = () vs undef
    my ($expr) = _split_modifier(\@k);
    return 0 unless $self->_expr_scalar_rooted($expr);
  }

  my @stmts = grep { $_->significant && !$_->isa('PPI::Statement::Null') }
              $sub->block->schildren;
  return 0 unless @stmts;
  my $last = $stmts[-1];
  return 1 if $last->isa('PPI::Statement::Break');   # checked above
  if (ref($last) eq 'PPI::Statement' || $last->isa('PPI::Statement::Variable')) {
    my @k = _strip_semi($last->schildren);
    shift @k if @k && $k[0]->isa('PPI::Token::Word') && $k[0]->content eq 'my';
    my ($expr) = _split_modifier(\@k);
    # for `my $x = INIT` the statement value is the assignment value
    return $self->_expr_scalar_rooted($expr) ? 1 : 0;
  }
  return 0;                                   # compound/other tail → sensitive
}

# The expression's ROOT forces scalar shape: an arithmetic/comparison operator
# (coerces its operands, yields one scalar), a scalar variable, a number, or a
# string literal.  A funcall root propagates the caller's context → NOT scalar.
# NOT included: && || // (context-transparent to their right operand) and
# x (repeats lists in list context).
my %SCALAR_ROOT_OP = map { $_ => 1 } qw(+ - * / % ** < > <= >= == != .
                                        eq ne lt gt le ge <=> cmp !);
sub _expr_scalar_rooted {
  my ($self, $parts) = @_;
  my @parts = _strip_semi(@{ $parts // [] });
  return 0 unless @parts;
  my $ok = eval {
    my $expr_o = Pl::PExpr->new(
      e           => \@parts,
      environment => $self->environment,
      parser      => $self->fallback_parser,
    );
    my ($id) = $expr_o->parse_expr_to_tree(\@parts);
    while (1) {
      my $node = $expr_o->get_a_node($id);
      my $kids = $expr_o->get_node_children($id);
      if ($expr_o->is_internal_node_type($node)) {
        my $t = $node->{type} // '';
        if ($t eq 'tree_val' && @$kids == 1) { $id = $kids->[0]; next }
        return 0;
      }
      return 1 if ref($node) eq 'PPI::Token::Operator' && @$kids
                  && $SCALAR_ROOT_OP{ $node->content };
      return 1 if ref($node) && $node->isa('PPI::Token::Number');
      return 1 if ref($node) && $node->isa('PPI::Token::Quote');
      return 1 if ref($node) eq 'PPI::Token::Symbol' && !@$kids
                  && $node->content =~ /^\$\w+$/;
      return 0;
    }
  };
  return $ok ? 1 : 0;
}

# ---------------------------------------------------------------- small helpers

sub _strip_semi {
  return grep { !($_->isa('PPI::Token::Structure') && $_->content eq ';') } @_;
}

# Split "EXPR if COND" style trailing statement modifiers at the top level.
sub _split_modifier {
  my ($parts) = @_;
  for my $i (1 .. $#$parts) {
    my $p = $parts->[$i];
    if ($p->isa('PPI::Token::Word') && $p->content =~ /^(if|unless|while|until|for|foreach)$/) {
      return ([@$parts[0 .. $i - 1]], $p->content, [@$parts[$i + 1 .. $#$parts]]);
    }
  }
  return ($parts, undef, undef);
}

sub _modifier_needs_fallback {
  my ($mod) = @_;
  return $mod && $mod !~ /^(?:if|unless)$/;
}

sub _apply_modifier {
  my ($form, $mod, $cond, $self, $stmt) = @_;
  return $form unless $mod;
  my $condform = $self->_lower_expr($cond, $stmt);
  return ['p-if', $condform, $form]          if $mod eq 'if';
  return ['p-if', ['p-!', $condform], $form] if $mod eq 'unless';
  die "Parser2 TODO: statement modifier '$mod'";   # unreachable (callers gate)
}

# `our $x` / `our @a` / `our (LIST)` [= INIT] → arrayref of runtime forms
# (possibly empty), or undef when the statement is not an `our` declaration.
# `our` names PACKAGE vars: no let — a defvar is hoisted to the section top
# (`_captured_decls`, read under the section's in-package), and the
# assignment lowers as a plain package-var assignment through the ordinary
# expression machinery (p-scalar-= / p-array-= / p-hash-= / p-list-=).
# NB: like v1, the `our` alias's lexical VISIBILITY is not modelled — the
# name simply resolves per-package (an `our $x` followed by `package Foo;
# print $x;` reads Foo::$x in both pipelines; Perl reads the alias).
sub _lower_our_decl {
  my ($self, $stmt) = @_;
  my @k = _strip_semi($stmt->schildren);
  return undef unless @k >= 2
    && $k[0]->isa('PPI::Token::Word') && $k[0]->content eq 'our';
  my @names;
  if ($k[1]->isa('PPI::Token::Symbol')) {
    @names = ($k[1]->content);
  } elsif ($k[1]->isa('PPI::Structure::List')) {
    @names = map  { $_->content }
             grep { $_->isa('PPI::Token::Symbol') } map { $_->tokens } $k[1];
  }
  my $bad = !@names
    || (grep { !/^[\$\@\%]\w+$/ } @names)
    || (@k > 2 && !($k[2]->isa('PPI::Token::Operator') && $k[2]->content eq '='));
  die "Parser2 TODO: unsupported our declaration: " . $stmt->content if $bad;
  for my $n (@names) {
    # A defvar of a let-bound name would proclaim it special and poison the
    # lexical lets (see _forward_global_decls) — shadowing our/my → v1.
    die "Parser2 TODO: our '$n' shadows a my-lexical\n"
      if $self->fallback_parser->{_let_bound_vars}{$n};
    push @{ $self->{_captured_decls} }, "(defvar $n " . _fresh_container($n) . ")";
  }
  return [] if @k == 2;
  # `NAMES = RHS` minus the `our` keyword is a plain (list) assignment.
  return [ $self->_lower_expr([@k[1 .. $#k]], $stmt) ];
}

# `my @a` / `my %h` / `my ($p, @q)` [= INIT] → (\@var_names, $has_init); else ().
sub _multi_decl {
  my ($self, $stmt) = @_;
  my @k = _strip_semi($stmt->schildren);
  return () unless @k >= 2
    && $k[0]->isa('PPI::Token::Word') && $k[0]->content eq 'my';
  my @vars;
  if ($k[1]->isa('PPI::Token::Symbol') && $k[1]->content =~ /^[\@\%]\w+$/) {
    @vars = ($k[1]->content);
  } elsif ($k[1]->isa('PPI::Structure::List')) {
    @vars = map  { $_->content }
            grep { $_->isa('PPI::Token::Symbol') } map { $_->tokens } $k[1];
    return () if !@vars || grep { !/^[\$\@\%]\w+$/ } @vars;
  } else {
    return ();
  }
  return (\@vars, 0) if @k == 2;
  return () unless $k[2]->isa('PPI::Token::Operator') && $k[2]->content eq '=';
  return (\@vars, 1);
}

sub _fresh_container {
  my ($var) = @_;
  my $sigil = substr($var, 0, 1);
  return '(make-array 0 :adjustable t :fill-pointer 0)' if $sigil eq '@';
  return "(make-hash-table :test 'equal)"               if $sigil eq '%';
  return '(make-p-box nil)';
}

# Whole-statement fallback: run one statement through the ORIGINAL parser's
# _process_element into a scratch section, then split the buckets — preamble/
# declarations/definitions lines are hoisted to the file top (they carry
# defvar/defconstant/eval-when forms that need top-level-ness), runtime lines
# embed at the statement's position as a raw form.  This is the statement-level
# twin of the _lower_expr fallback seam.
#
# Statements whose v1 lowering opens a scope spanning to block end (`local`,
# `delete local` — counted in _local_let_depth) leave the runtime text with
# open parens; _fallback_stmt_capture reports that surplus so _lower_block can
# nest the block remainder inside (raw_wrap).  _fallback_stmt itself is for
# self-contained statements only and treats a surplus as an unsupported shape.
sub _fallback_stmt {
  my ($self, $stmt) = @_;
  my ($text, $opens) = $self->_fallback_stmt_capture($stmt);
  die "Parser2 TODO: statement fallback left $opens open scope(s): " . $stmt->content
    if $opens;
  return () unless defined $text;
  return raw($text);
}

# A statement v1's local machinery owns: `local …;` (Statement::Variable with
# declarator `local`) or standalone `delete local …;` (plain Statement).
sub _is_local_stmt {
  my ($self, $stmt) = @_;
  my @k = $stmt->schildren;
  return 0 unless @k && $k[0]->isa('PPI::Token::Word');
  return 1 if $stmt->isa('PPI::Statement::Variable') && $k[0]->content eq 'local';
  return 1 if $k[0]->content eq 'delete'
    && $k[1] && $k[1]->isa('PPI::Token::Word') && $k[1]->content eq 'local';
  return 0;
}

# `local` scopes to the end of the enclosing block: v1 emits the save/restore
# form(s) OPEN and counts them in _local_let_depth (closed at block end by
# emit-order bookkeeping).  v2's tree structure does the same thing by
# construction — nest the lowered block remainder inside the open text via
# raw_wrap.  Degenerate locals that open no scope (`local $#a = N`, skipped
# stash locals) come back with 0 opens and embed as a plain raw statement.
sub _lower_local {
  my ($self, $stmt, $rest, $vi, $tail_ctx) = @_;
  my ($text, $opens) = $self->_fallback_stmt_capture($stmt);
  my @rest_forms = $self->_lower_block($rest, $vi, $tail_ctx);
  return ((defined $text ? (raw($text)) : ()), @rest_forms) unless $opens;
  return raw_wrap($text, $opens, @rest_forms);
}

sub _fallback_stmt_capture {
  my ($self, $stmt) = @_;
  my $p = $self->fallback_parser;
  my @saved = ($p->_sections, $p->_cur_bucket, $p->indent_level,
               $p->{_local_let_depth});
  $p->_sections([]);
  $p->_cur_bucket('runtime');
  $p->_open_section('pcl');
  $p->indent_level(0);
  $p->{_local_let_depth} = 0;
  $p->_process_element($stmt);
  my $opens = $p->{_local_let_depth};
  my @runtime;
  for my $sec (@{ $p->_sections }) {
    push @{ $self->{_captured_decls} },
      grep { /\S/ } @{$sec->{preamble}}, @{$sec->{declarations}}, @{$sec->{definitions}};
    push @runtime, grep { /\S/ } @{$sec->{runtime}};
  }
  $p->_sections($saved[0]);
  $p->_cur_bucket($saved[1]);
  $p->indent_level($saved[2]);
  $p->{_local_let_depth} = $saved[3];
  return (@runtime ? join("\n", @runtime) : undef, $opens);
}

# `my $x` / `my $x = INIT` → ($name, \@init_parts | undef); else ().
sub _single_scalar_decl {
  my ($self, $stmt) = @_;
  my @k = _strip_semi($stmt->schildren);
  return () unless @k >= 2
    && $k[0]->isa('PPI::Token::Word') && $k[0]->content eq 'my'
    && $k[1]->isa('PPI::Token::Symbol') && $k[1]->content =~ /^\$\w+$/;
  my $name = $k[1]->content;
  return ($name, undef) if @k == 2;
  return () unless $k[2]->isa('PPI::Token::Operator') && $k[2]->content eq '=';
  return ($name, [@k[3 .. $#k]]);
}

sub _cond_parts {
  my ($cond) = @_;
  return map { $_->schildren } grep { $_->isa('PPI::Statement') } $cond->children;
}

# Step statement that is EXACTLY `$i++` / `++$i` / `$i--` / `--$i` for the
# given counter → '+' or '-'; anything else → undef.
sub _pure_incr_step {
  my ($step_s, $name) = @_;
  my @k = _strip_semi($step_s->schildren);
  return undef unless @k == 2;
  my ($a, $b) = @k;
  ($a, $b) = ($b, $a) if $a->isa('PPI::Token::Operator');   # prefix form
  return undef unless $a->isa('PPI::Token::Symbol') && $a->content eq $name
    && $b->isa('PPI::Token::Operator');
  return '+' if $b->content eq '++';
  return '-' if $b->content eq '--';
  return undef;
}

1;
