;;;; Generated from test-runtime-simple.pl
;;;; Run with: sbcl --load pcl-runtime.lisp --load test-runtime-simple-run.lisp

(in-package :pcl)

;; Declare all variables used
(pl-let (($a nil) ($b nil) ($x nil) ($n nil)
         ($greeting nil) ($name nil) ($msg nil) ($str nil) ($repeated nil)
         ($p nil) ($q nil) ($r nil) ($s1 nil) ($s2 nil)
         ($i nil) ($sum nil) ($j nil) ($product nil)
         ($val nil) ($result nil)
         ($t nil) ($f nil) ($default nil) ($value nil))

  ;; === Arithmetic ===
  (pl-say "=== Arithmetic ===")
  (pl-setf $a 10)
  (pl-setf $b 3)
  (pl-say (pl-. (pl-. (pl-. "a=" $a) ", b=") $b))
  (pl-say (pl-. "a+b=" (pl-+ $a $b)))
  (pl-say (pl-. "a-b=" (pl-- $a $b)))
  (pl-say (pl-. "a*b=" (pl-* $a $b)))
  (pl-say (pl-. "a%b=" (pl-% $a $b)))
  (pl-say (pl-. "a**b=" (pl-** $a $b)))

  (pl-say "")
  (pl-say "=== Increment ===")
  (pl-setf $x 5)
  (pl-say (pl-. "x=" $x))
  (pl-say (pl-. "x++=" (pl-++-post $x)))
  (pl-say (pl-. "now x=" $x))
  (pl-say (pl-. "++x=" (pl-++-pre $x)))
  (pl-say (pl-. "now x=" $x))

  (pl-say "")
  (pl-say "=== Compound ===")
  (pl-setf $n 100)
  (pl-say (pl-. "n=" $n))
  (pl-incf $n 10)
  (pl-say (pl-. "n+10=" $n))
  (pl-decf $n 5)
  (pl-say (pl-. "n-5=" $n))
  (pl-*= $n 2)
  (pl-say (pl-. "n*2=" $n))

  (pl-say "")
  (pl-say "=== Strings ===")
  (pl-setf $greeting "Hello")
  (pl-setf $name "World")
  (pl-setf $msg (pl-. (pl-. (pl-. $greeting ", ") $name) "!"))
  (pl-say (pl-. "msg=" $msg))
  (pl-say (pl-. "len=" (pl-length $msg)))
  (pl-setf $str "test")
  (pl-.= $str "_suffix")
  (pl-say (pl-. "concat=" $str))
  (pl-setf $repeated (pl-x "ab" 4))
  (pl-say (pl-. "repeat=" $repeated))

  (pl-say "")
  (pl-say "=== Compare ===")
  (pl-setf $p 5)
  (pl-setf $q 10)
  (pl-setf $r 5)
  (pl-say (pl-. "p==r: " (pl-if (pl-== $p $r) "T" "F")))
  (pl-say (pl-. "p==q: " (pl-if (pl-== $p $q) "T" "F")))
  (pl-say (pl-. "p<q: " (pl-if (pl-< $p $q) "T" "F")))
  (pl-say (pl-. "p<=r: " (pl-if (pl-<= $p $r) "T" "F")))
  (pl-setf $s1 "apple")
  (pl-setf $s2 "banana")
  (pl-say (pl-. "lt: " (pl-if (pl-lt $s1 $s2) "T" "F")))
  (pl-say (pl-. "eq: " (pl-if (pl-eq $s1 $s1) "T" "F")))

  (pl-say "")
  (pl-say "=== While ===")
  (pl-setf $i 0)
  (pl-setf $sum 0)
  (pl-while (pl-< $i 5)
    (pl-incf $sum $i)
    (pl-say (pl-. (pl-. (pl-. "i=" $i) " sum=") $sum))
    (pl-++-post $i))
  (pl-say (pl-. "final=" $sum))

  (pl-say "")
  (pl-say "=== For ===")
  (pl-setf $product 1)
  (pl-for ((pl-setf $j 1))
          ((pl-<= $j 5))
          ((pl-++-post $j))
    (pl-*= $product $j)
    (pl-say (pl-. (pl-. (pl-. "j=" $j) " prod=") $product)))
  (pl-say (pl-. "5!=" $product))

  (pl-say "")
  (pl-say "=== Cond ===")
  (pl-setf $val 42)
  (pl-if (pl-> $val 50)
    (progn (pl-say "gt50"))
    (pl-if (pl-> $val 40)
      (progn (pl-say "gt40"))
      (progn (pl-say "le40"))))
  (pl-setf $result (pl-if (pl-> $val 0) "pos" "neg"))
  (pl-say (pl-. "sign=" $result))

  (pl-say "")
  (pl-say "=== Logic ===")
  (pl-setf $t 1)
  (pl-setf $f 0)
  (pl-say (pl-. "t&&t=" (pl-&& $t $t)))
  (pl-say (pl-. "t&&f=" (pl-&& $t $f)))
  (pl-say (pl-. "f||t=" (pl-|| $f $t)))
  (pl-say (pl-. "f||f=" (pl-|| $f $f)))
  (pl-setf $default 0)
  (pl-setf $value (pl-|| $default 42))
  (pl-say (pl-. "or42=" $value))

  (pl-say "")
  (pl-say "=== Done ==="))
