#!/usr/bin/env perl
# Copyright (c) 2025-2026 the PCL authors
# This is free software; you can redistribute it and/or modify it under the
# same terms as the Perl 5 programming language system itself.
# SPDX-License-Identifier: Artistic-1.0-Perl OR GPL-1.0-or-later
#
# dup-census.pl -- the DUPLICATED-CODE census (task #379 §ADDED, s411).
#
# CLAUDE.md rule 11 ("reuse, don't duplicate") is a rule about NEW code; this
# is its census over the code that already exists: every run of >= K
# normalized source lines that occurs two or more times, ranked by the number
# of lines an extraction would delete (run length x (copies - 1)).  Two
# levels are reported for every run:
#
#   EXACT  -- the lines are identical after whitespace/comment normalization;
#   SHAPE  -- identical after ALSO abstracting variable names, numbers and
#             string literals ($foo -> $V, 42 -> N, "text" -> "S"), which is
#             what "the same five lines with the names changed" looks like.
#
# A run's members are the places it occurs (file:start-end, enclosing sub).
# Optionally each member is tagged with the enclosing sub's dynamic call
# count from tools/sub-call-census.pl (--calls FILE), so a worklist can tell
# a hot per-token path from cold setup code: an extraction on a hot path
# ships with a compile-time measurement, a cold one is free.
#
# What this tool does NOT decide: whether a cluster SHOULD be extracted.
# Boilerplate that reads better repeated (a five-line accessor, an argument
# unpack) will score; the CLAUDE.md-11 question -- does the family already
# have a shared upstream point? -- is answered by a reader, per cluster.
#
# Usage:
#   tools/dup-census.pl                       # default file set, markdown to stdout
#   tools/dup-census.pl --min-lines 6 --tsv out.tsv Pl/Parser2.pm Pl/Parser.pm
#   tools/dup-census.pl --calls calls.tsv     # tag members hot/cold
#   tools/dup-census.pl --top 40              # how many clusters to print
#
# Perl (.pm/.pl/shebang scripts) and Lisp (.lisp) files are normalized by
# their own rules and never compared across the language boundary.

use v5.20;
use strict;
use warnings;
use Getopt::Long;
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use FindBin;

my $ROOT = abs_path("$FindBin::Bin/..");

my $min_lines = 5;       # K: shingle length = shortest reportable run
my $min_subst = 3;       # substantive lines a run must contain
my $top       = 60;
my $tsv_out;
my $calls_file;
my $level_opt = 'both';  # exact | shape | both
GetOptions(
  'min-lines=i' => \$min_lines,
  'min-subst=i' => \$min_subst,
  'top=i'       => \$top,
  'tsv=s'       => \$tsv_out,
  'calls=s'     => \$calls_file,
  'level=s'     => \$level_opt,
) or die "usage: $0 [--min-lines K] [--top N] [--tsv FILE] [--calls FILE] [--level exact|shape|both] [FILES...]\n";

my @files = @ARGV ? @ARGV : default_files();
my %calls = $calls_file ? read_calls($calls_file) : ();

# ---------------------------------------------------------------- units
# One unit per file: a list of kept lines, each with its original line
# number, exact and shape keys, a substantiveness weight and its enclosing
# sub name.
my @units = map { read_unit($_) } @files;

my @levels = $level_opt eq 'both' ? qw(x s) : $level_opt eq 'exact' ? ('x') : ('s');
my @runs;
for my $lv (@levels) {
  push @runs, find_runs($lv, \@units);
}
# An EXACT run is the identical core of some SHAPE run (the same copies,
# each extent contained in the SHAPE member's): report the SHAPE run once and
# carry the exact core length on it, instead of listing both.
my @kept = absorb_exact_cores(\@runs);
@runs = sort { $b->{score} <=> $a->{score} || $b->{lines} <=> $a->{lines} } @kept;

my @families = group_families(\@runs, \@units);
report_markdown(\@runs, \@units, \@families);
write_tsv($tsv_out, \@runs, \@units, \@families) if $tsv_out;
exit 0;

# ---------------------------------------------------------------- inputs
sub default_files {
  my @f;
  push @f, glob("$ROOT/Pl/*.pm"), glob("$ROOT/Pl/PExpr/*.pm");
  # Hand-written Lisp only: the three transpiled artifacts (pcl-pack,
  # pcl-mro, pcl-warnings) are generated by PCL itself and out of scope.
  push @f, map { "$ROOT/cl/$_" } qw(pcl-runtime.lisp pcl-test.lisp pcl-xs.lisp skip-registry.lisp);
  push @f, glob("$ROOT/tools/*.pl"), glob("$ROOT/tools/lib/*.pm");
  push @f, map { "$ROOT/tools/$_" } qw(install-pcl pcl-conform pcl-xs-install pclperl-for-tests tag-license build-pclxs);
  push @f, map { "$ROOT/$_" } qw(pl2cl runpcl runt clt sweep-perl-tests.pl);
  push @f, "$ROOT/Pl/t/PCLCore.pm";
  return grep { -f $_ } @f;
}

sub read_calls {
  my ($path) = @_;
  open my $fh, '<', $path or die "$0: cannot read --calls $path: $!\n";
  my %c;
  while (my $line = <$fh>) {
    chomp $line;
    next if $line =~ /^#/ || $line !~ /\t/;
    my ($name, $n) = split /\t/, $line;
    $c{$name} = $n;
  }
  return %c;
}

sub read_unit {
  my ($path) = @_;
  my $rel = $path;
  $rel =~ s{^\Q$ROOT\E/}{};
  my $lang = $path =~ /\.lisp$/ ? 'lisp' : 'perl';
  open my $fh, '<', $path or die "$0: cannot read $path: $!\n";
  my @lines;
  my $sub = '(file)';
  my $in_pod = 0;
  my $n = 0;
  while (my $raw = <$fh>) {
    $n++;
    chomp $raw;
    if ($lang eq 'perl') {
      last if $raw =~ /^__(?:END|DATA)__\s*$/;
      if ($in_pod) { $in_pod = 0 if $raw =~ /^=cut\b/; next }
      if ($raw =~ /^=\w/) { $in_pod = 1; next }
      $sub = $1 if $raw =~ /^\s*sub\s+([\w:]+)/;
    } else {
      $sub = $2 if $raw =~ /^\((def(?:un|macro|method|generic|var|parameter|constant|struct|type|ine-[\w-]+))\s+([^\s()]+)/;
    }
    my ($x, $s, $w) = normalize($raw, $lang);
    next if !defined $x;
    push @lines, { n => $n, x => $x, s => $s, w => $w, sub => $sub };
  }
  return { file => $rel, lang => $lang, lines => \@lines };
}

# Returns (exact, shape, weight) or () for a line that carries no code.
sub normalize {
  my ($raw, $lang) = @_;
  my $t = $raw;
  if ($lang eq 'lisp') {
    $t =~ s/^\s*;.*$//;
    # a trailing comment: ";" preceded by space, outside the common ";"-in-a-
    # string case, which is rare enough in this runtime to accept.
    $t =~ s/\s;[^"]*$// if $t !~ /"[^"]*;[^"]*"/;
  } else {
    return () if $t =~ /^\s*#/;
    # a trailing comment of the usual "  # ..." spelling; "$#a" and "#{" in
    # a regex are not preceded by whitespace and survive.
    $t =~ s/\s+#\s.*$//;
  }
  $t =~ s/^\s+//; $t =~ s/\s+$//; $t =~ s/\s+/ /g;
  return () if $t eq '';
  my $exact = $t;
  my $shape = $t;
  if ($lang eq 'lisp') {
    $shape =~ s/"(?:[^"\\]|\\.)*"/"S"/g;
    $shape =~ s/(?<![\w-])-?\d+(?:\.\d+)?(?![\w-])/N/g;
  } else {
    $shape =~ s/"(?:[^"\\]|\\.)*"/"S"/g;
    $shape =~ s/'(?:[^'\\]|\\.)*'/'S'/g;
    $shape =~ s/(?<![\w\$\@%&])\d+(?:\.\d+)?\b/N/g;
    $shape =~ s/\$#\{?\w+\}?/\$#V/g;
    $shape =~ s/([\$\@%&])(?!\{)(?:\w+::)*\w+/${1}V/g;
  }
  # weight: 1 for a substantive line, 0 for a closer/opener/one-word line
  my $w = ($exact =~ /^[\)\}\];,\(\{]*$/ || length($exact) < 12) ? 0 : 1;
  return ($exact, $shape, $w);
}

# ---------------------------------------------------------------- runs
sub find_runs {
  my ($lv, $units) = @_;
  my $k = $min_lines;
  # shingle -> [ [u,i], ... ]   (only within one language)
  my %group;
  for my $u (0 .. $#$units) {
    my $L = $units->[$u]{lines};
    my $lang = $units->[$u]{lang};
    for my $i (0 .. @$L - $k) {
      my $key = $lang . "\0" . join("\n", map { $L->[$_]{$lv} } $i .. $i + $k - 1);
      push @{ $group{$key} }, [$u, $i];
    }
  }
  # gid per position, members per gid
  my (%gid_of, @members);
  for my $key (keys %group) {
    my $m = $group{$key};
    next if @$m < 2;
    my $g = @members;
    push @members, $m;
    $gid_of{"$_->[0]:$_->[1]"} = $g for @$m;
  }
  my $memkey = sub {                       # membership shifted by $d
    my ($g, $d) = @_;
    return join ',', sort map { "$_->[0]:" . ($_->[1] + $d) } @{ $members[$g] };
  };
  my @runs;
  for my $g (0 .. $#members) {
    my ($u0, $i0) = @{ $members[$g][0] };
    # smallest member decides whether this position STARTS a run
    my ($su, $si) = (sort { $a->[0] <=> $b->[0] || $a->[1] <=> $b->[1] } @{ $members[$g] })[0]->@*;
    next if "$u0:$i0" ne "$su:$si";
    my $prev = $gid_of{"$su:" . ($si - 1)};
    next if defined $prev && $memkey->($prev, 1) eq $memkey->($g, 0);   # continues an earlier run
    my $len = 1;                             # in shingles
    while (1) {
      my $nx = $gid_of{"$su:" . ($si + $len)};
      last if !defined $nx || $memkey->($nx, 0) ne $memkey->($g, $len);
      $len++;
    }
    my $nlines = $len + $k - 1;
    my @mem = map { { u => $_->[0], i => $_->[1], len => $nlines } } @{ $members[$g] };
    next if members_overlap(\@mem);
    my $L = $units->[$su]{lines};
    my $subst = 0;
    $subst += $L->[$_]{w} for $si .. $si + $nlines - 1;
    next if $subst < $min_subst || $subst * 2 < $nlines;
    push @runs, {
      level => $lv, lines => $nlines, copies => scalar(@mem),
      score => $nlines * (@mem - 1), members => \@mem, subst => $subst,
    };
  }
  return @runs;
}

# Drop every EXACT run that is contained, member for member, in a SHAPE run
# with the same copies; the SHAPE run carries the exact core length.
sub absorb_exact_cores {
  my ($runs) = @_;
  my @shape = grep { $_->{level} eq 's' } @$runs;
  my @out = @shape;
  EXACT: for my $x (grep { $_->{level} eq 'x' } @$runs) {
    my @xm = sort { $a->{u} <=> $b->{u} || $a->{i} <=> $b->{i} } @{ $x->{members} };
    for my $s (@shape) {
      next if @{ $s->{members} } != @xm;
      my @sm = sort { $a->{u} <=> $b->{u} || $a->{i} <=> $b->{i} } @{ $s->{members} };
      my $inside = 1;
      for my $j (0 .. $#xm) {
        my ($p, $q) = ($xm[$j], $sm[$j]);
        $inside = 0, last if $p->{u} != $q->{u} || $p->{i} < $q->{i} || $p->{i} + $p->{len} > $q->{i} + $q->{len};
      }
      if ($inside) {
        $s->{exact_core} = $x->{lines} if ($s->{exact_core} // 0) < $x->{lines};
        next EXACT;
      }
    }
    push @out, $x;
  }
  return @out;
}

sub members_overlap {
  my ($mem) = @_;
  my @m = sort { $a->{u} <=> $b->{u} || $a->{i} <=> $b->{i} } @$mem;
  for my $j (1 .. $#m) {
    my ($p, $q) = ($m[$j-1], $m[$j]);
    return 1 if $p->{u} == $q->{u} && $q->{i} < $p->{i} + $p->{len};
  }
  return 0;
}

# ---------------------------------------------------------------- output
sub member_desc {
  my ($m, $units) = @_;
  my $unit = $units->[$m->{u}];
  my $L = $unit->{lines};
  my ($a, $b) = ($L->[$m->{i}]{n}, $L->[$m->{i} + $m->{len} - 1]{n});
  my $first = (grep { $L->[$_]{w} } $m->{i} .. $m->{i} + $m->{len} - 1)[0] // $m->{i};
  my $sub = $L->[$first]{sub};
  my $hot = '';
  if (%calls) {
    my ($pkg) = pkg_of($unit->{file});
    my $c = $calls{"$pkg\::$sub"} // $calls{$sub};
    $hot = defined $c ? " calls=$c" : '';
  }
  return "$unit->{file}:$a-$b [$sub]$hot";
}

sub pkg_of {
  my ($file) = @_;
  my $p = $file;
  $p =~ s{\.pm$}{}; $p =~ s{/}{::}g;
  return $p;
}

# Clusters whose member extents overlap (same file, overlapping lines) are one
# extraction TARGET — the "subscript scanner" family in StringInterpolation
# shows up as eight clusters of different lengths and copy counts.  Union-find
# over overlapping extents; a family is ranked by the sum of its clusters'
# deletable lines (an over-count where clusters nest, so it is a rank, not a
# promise).
sub group_families {
  my ($runs, $units) = @_;
  my @parent = (0 .. $#$runs);
  my $find;
  $find = sub { my ($x) = @_; $parent[$x] = $find->($parent[$x]) if $parent[$x] != $x; return $parent[$x] };
  my $union = sub { my ($a, $b) = @_; $parent[$find->($a)] = $find->($b) };
  # A minimum-length SHAPE cluster is often a generic idiom (`for my $i …
  # substr …`) that lands in unrelated subs; it may belong to a family but
  # must not BRIDGE two families, so it does not take part in the union.
  my %by_unit;
  for my $r (0 .. $#$runs) {
    next if $runs->[$r]{level} eq 's' && $runs->[$r]{lines} <= $min_lines;
    push @{ $by_unit{ $_->{u} } }, [$_->{i}, $_->{i} + $_->{len} - 1, $r] for @{ $runs->[$r]{members} };
  }
  # Two extents are the SAME code region when they share at least half of the
  # shorter one; a one-line touch between two unrelated clusters is not (a
  # generic 5-line shape that appears in three files would otherwise chain
  # every family into one).
  for my $u (keys %by_unit) {
    my @m = sort { $a->[0] <=> $b->[0] } @{ $by_unit{$u} };
    for my $j (0 .. $#m) {
      for my $k ($j + 1 .. $#m) {
        last if $m[$k][0] > $m[$j][1];
        my $ov = (($m[$j][1] < $m[$k][1] ? $m[$j][1] : $m[$k][1]) - $m[$k][0] + 1);
        my $short = ($m[$j][1] - $m[$j][0] < $m[$k][1] - $m[$k][0] ? $m[$j][1] - $m[$j][0] : $m[$k][1] - $m[$k][0]) + 1;
        $union->($m[$j][2], $m[$k][2]) if $ov * 2 >= $short;
      }
    }
  }
  my %fam;
  push @{ $fam{ $find->($_) } }, $_ for 0 .. $#$runs;
  my @out;
  for my $k (keys %fam) {
    my @rs = sort { $runs->[$b]{score} <=> $runs->[$a]{score} } @{ $fam{$k} };
    my $score = 0;
    $score += $runs->[$_]{score} for @rs;
    my %where;
    for my $r (@rs) {
      for my $m (@{ $runs->[$r]{members} }) {
        my $L = $units->[$m->{u}]{lines};
        my $first = (grep { $L->[$_]{w} } $m->{i} .. $m->{i} + $m->{len} - 1)[0] // $m->{i};
        $where{ $units->[$m->{u}]{file} . " [" . $L->[$first]{sub} . "]" }++;
      }
    }
    push @out, { runs => \@rs, score => $score, where => [ sort keys %where ] };
  }
  return sort { $b->{score} <=> $a->{score} } @out;
}

sub report_markdown {
  my ($runs, $units, $families) = @_;
  my %fam_of;
  for my $fi (0 .. $#$families) { $fam_of{$_} = $fi + 1 for @{ $families->[$fi]{runs} } }
  my $date = do { my @t = localtime; sprintf '%04d-%02d-%02d', $t[5]+1900, $t[4]+1, $t[3] };
  print "# duplicated-code census — $date\n\n";
  printf "Files: %d.  Shingle: %d lines.  Runs found: %d (exact %d, shape-only %d).\n\n",
    scalar(@$units), $min_lines, scalar(@$runs),
    scalar(grep { $_->{level} eq 'x' } @$runs), scalar(grep { $_->{level} eq 's' } @$runs);

  # per-file totals: deletable lines = sum over runs of lines x (copies-1),
  # attributed to the file of each NON-first member (the copy that would go).
  my %del;
  for my $r (@$runs) {
    my @m = sort { $a->{u} <=> $b->{u} || $a->{i} <=> $b->{i} } @{ $r->{members} };
    shift @m;
    $del{ $units->[$_->{u}]{file} }{ $r->{level} } += $r->{lines} for @m;
  }
  print "## Deletable lines by file (a copy's lines, not the original's)\n\n";
  print "| file | exact | shape | total |\n|---|---|---|---|\n";
  for my $f (sort { ($del{$b}{x}//0)+($del{$b}{s}//0) <=> ($del{$a}{x}//0)+($del{$a}{s}//0) } keys %del) {
    my ($x, $s) = ($del{$f}{x} // 0, $del{$f}{s} // 0);
    printf "| %s | %d | %d | %d |\n", $f, $x, $s, $x + $s;
  }
  my $tx = 0; my $ts = 0;
  for my $f (keys %del) { $tx += $del{$f}{x} // 0; $ts += $del{$f}{s} // 0 }
  printf "| **total** | %d | %d | %d |\n\n", $tx, $ts, $tx + $ts;

  print "## Families (clusters with overlapping extents = one extraction target), ranked\n\n";
  my $fn = 0;
  for my $f (@$families) {
    last if ++$fn > $top;
    printf "%d. **~%d** — clusters %s — %s\n", $fn, $f->{score},
      join(", ", map { $_ + 1 } @{ $f->{runs} }), join("; ", @{ $f->{where} });
  }
  printf "\n(%d families in all.)\n\n", scalar(@$families);

  print "## Clusters, ranked by lines an extraction would delete\n\n";
  my $n = 0;
  for my $r (@$runs) {
    last if ++$n > $top;
    my $lvl = $r->{level} eq 'x' ? 'EXACT' : 'SHAPE';
    printf "### %d. %s — %d lines × %d copies (deletes %d)%s — family %d\n\n", $n, $lvl, $r->{lines}, $r->{copies}, $r->{score},
      ($r->{exact_core} ? " — exact core $r->{exact_core} lines" : ""), $fam_of{$n - 1};
    print "- $_\n" for map { member_desc($_, $units) } sort { $a->{u} <=> $b->{u} || $a->{i} <=> $b->{i} } @{ $r->{members} };
    my $m = $r->{members}[0];
    my $L = $units->[$m->{u}]{lines};
    my @preview = map { $L->[$_]{x} } $m->{i} .. ($m->{i} + ($r->{lines} > 4 ? 3 : $r->{lines} - 1));
    print "\n```\n", join("\n", @preview), ($r->{lines} > 4 ? "\n..." : ''), "\n```\n\n";
  }
}

sub write_tsv {
  my ($path, $runs, $units, $families) = @_;
  my %fam_of;
  for my $fi (0 .. $#$families) { $fam_of{$_} = $fi + 1 for @{ $families->[$fi]{runs} } }
  open my $fh, '>', $path or die "$0: cannot write $path: $!\n";
  print $fh join("\t", qw(rank family level lines copies deletes members)), "\n";
  my $n = 0;
  for my $r (@$runs) {
    $n++;
    print $fh join("\t", $n, $fam_of{$n - 1}, ($r->{level} eq 'x' ? 'EXACT' : 'SHAPE'), $r->{lines}, $r->{copies}, $r->{score},
      join('; ', map { member_desc($_, $units) } sort { $a->{u} <=> $b->{u} || $a->{i} <=> $b->{i} } @{ $r->{members} })), "\n";
  }
  close $fh;
  print STDERR "wrote $path ($n rows)\n";
}
